export interface StoryWeaverStory {
  id: string;
  storyId: string;
  titleEn: string;
  titleTa: string;
  author: string;
  level: '1' | '2' | '3' | '4';
  levelLabelEn: string;
  levelLabelTa: string;
  targetGrades: string;
  coverUrl: string;
  embedUrl: string;
  descriptionEn: string;
  descriptionTa: string;
  readingPoints: number;
  pagesCount: number;
  tags: string[];
}

export function toStoryWeaverEmbedUrl(urlOrSlug: string): string {
  if (!urlOrSlug) return '';
  const trimmed = urlOrSlug.trim();

  // If already in full reader embed format with mode=read:
  if (trimmed.includes('/stories/embed/reader/') && trimmed.includes('mode=read')) {
    return trimmed;
  }

  // Match any StoryWeaver story URL pattern:
  // e.g. https://storyweaver.org.in/en/stories/embed/reader/123-slug
  // e.g. https://storyweaver.org.in/en/stories/embed/123-slug
  // e.g. https://storyweaver.org.in/en/stories/123-slug/read
  // e.g. https://storyweaver.org.in/stories/123-slug
  const urlMatch = trimmed.match(/storyweaver\.org\.in\/(?:[a-zA-Z]{2}\/)?stories\/(?:embed\/(?:reader\/)?)?([a-zA-Z0-9_\-]+)/);
  if (urlMatch && urlMatch[1]) {
    const slug = urlMatch[1];
    return `https://storyweaver.org.in/en/stories/embed/reader/${slug}?mode=read`;
  }

  // If raw slug or numeric ID passed directly: 619123-en-akkavum-naanum or 378
  if (/^[a-zA-Z0-9_\-]+$/.test(trimmed)) {
    return `https://storyweaver.org.in/en/stories/embed/reader/${trimmed}?mode=read`;
  }

  return trimmed;
}

export const STORYWEAVER_STORIES: StoryWeaverStory[] = [
  {
    "id": "sw_619123",
    "storyId": "619123-en-akkavum-naanum",
    "titleEn": "My Sister and Me",
    "titleTa": "என் அக்காவும் நானும்",
    "author": "Anitha Selvanathan, Kanchan Bannerjee",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/722794/size3/f143a6160fb50b198048ab8960fafc03.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/619123-en-akkavum-naanum?mode=read",
    "descriptionEn": "A heartwarming story about two sisters who fight a lot, but love each other very much.",
    "descriptionTa": "நிறைய சண்டைப் போடும், ஆனால் ரொம்ப பாசமாக இருக்கும் இரு சகோதரிகளைப் பற்றிய சிறுகதை.",
    "readingPoints": 50,
    "pagesCount": 8,
    "tags": [
      "family",
      "sisters",
      "love",
      "everyday"
    ]
  },
  {
    "id": "sw_378",
    "storyId": "378-en-nanbargal",
    "titleEn": "என் நண்பர்கள்",
    "titleTa": "என் நண்பர்கள்",
    "author": "Praba Ram, Sheela Preuitt",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/721912/size3/066122b27bde426119a6c1d4284800f1.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/378-en-nanbargal?mode=read",
    "descriptionEn": "எனக்கு  பல நண்பர்கள் உள்ளனர். அவர்கள் அனைவரையும் விரும்புகிறேன். ஆனால் அவருள் ஒருவர் மட்டும் மிகவும் சிறந்தவர் ஆவார்.",
    "descriptionTa": "எனக்கு  பல நண்பர்கள் உள்ளனர். அவர்கள் அனைவரையும் விரும்புகிறேன். ஆனால் அவருள் ஒருவர் மட்டும் மிகவும் சிறந்தவர் ஆவார்.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_22929",
    "storyId": "22929-kaattu-poonai-kaattu-poonai",
    "titleEn": "காட்டுப் பூனை! காட்டுப் பூனை!",
    "titleTa": "காட்டுப் பூனை! காட்டுப் பூனை!",
    "author": "Bhuvana Shiv",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/722383/size3/b67b65b0b4e07eecc3cd0aa184e1548c.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/22929-kaattu-poonai-kaattu-poonai?mode=read",
    "descriptionEn": "இந்தியாவின் வனங்களிலிருக்கும் பலவகைப் பூனைகளை சந்திக்கலாம், வாருங்கள்!",
    "descriptionTa": "இந்தியாவின் வனங்களிலிருக்கும் பலவகைப் பூனைகளை சந்திக்கலாம், வாருங்கள்!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_608",
    "storyId": "608-nillavum-toppiyum",
    "titleEn": "நிலாவும் தொப்பியும்",
    "titleTa": "நிலாவும் தொப்பியும்",
    "author": "S. Jayaraman",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/700911/size3/a7997747b4c2afe36ad258eb24979534.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/608-nillavum-toppiyum?mode=read",
    "descriptionEn": "வெயில்காலத்தில் தொப்பியணிய விருப்பமா? வேறு யாருக்கெல்லாம் தொப்பியணியப் பிடிக்கும் என்று இந்த அழகான புத்தகத்திலிருந்து தெரிந்துகொள்ளுங்கள்.",
    "descriptionTa": "வெயில்காலத்தில் தொப்பியணிய விருப்பமா? வேறு யாருக்கெல்லாம் தொப்பியணியப் பிடிக்கும் என்று இந்த அழகான புத்தகத்திலிருந்து தெரிந்துகொள்ளுங்கள்.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_12161",
    "storyId": "12161-kaaththaadi",
    "titleEn": "காத்தாடி!",
    "titleTa": "காத்தாடி!",
    "author": "Anitha Ramkumar",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/117638/size3/ac6a77ff9d0dd2a0a61098ad0557ff0c.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/12161-kaaththaadi?mode=read",
    "descriptionEn": "புத்தகத்தைத் திறந்துபாருங்கள். காத்தாடியை கண்டு பிடியுங்கள். அப்புறம், அதற்கு என்ன ஆகின்றது என்று பாருங்கள். கதையையும் வர்லி ஓவியங்களையும் அனுபவித்து மகிழுங்கள்.",
    "descriptionTa": "புத்தகத்தைத் திறந்துபாருங்கள். காத்தாடியை கண்டு பிடியுங்கள். அப்புறம், அதற்கு என்ன ஆகின்றது என்று பாருங்கள். கதையையும் வர்லி ஓவியங்களையும் அனுபவித்து மகிழுங்கள்.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_47929",
    "storyId": "47929-oru-ilaiyin-kathai",
    "titleEn": "ஒரு இலையின் கதை",
    "titleTa": "ஒரு இலையின் கதை",
    "author": "Rajam Anand",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/99508/size3/2a551b9353131eff1cbbd72774fa8d32.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/47929-oru-ilaiyin-kathai?mode=read",
    "descriptionEn": "ஒரு சின்ன பச்சை-மஞ்சள் இலையோடு சேர்ந்து பயணிக்கலாம், வாருங்கள்!",
    "descriptionTa": "ஒரு சின்ன பச்சை-மஞ்சள் இலையோடு சேர்ந்து பயணிக்கலாம், வாருங்கள்!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_62767",
    "storyId": "62767-malar-kattiya-veedu",
    "titleEn": "மலர் கட்டிய வீடு",
    "titleTa": "மலர் கட்டிய வீடு",
    "author": "I K Lenin Tamilkovan",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/715434/size3/5613393324b2c4300bc530bb88cb1e16.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/62767-malar-kattiya-veedu?mode=read",
    "descriptionEn": "மலருக்கு கட்டடங்கள் கட்டுவதென்றால் பிடிக்கும். இன்று அவள் என்ன கட்டப் போகிறாள்?",
    "descriptionTa": "மலருக்கு கட்டடங்கள் கட்டுவதென்றால் பிடிக்கும். இன்று அவள் என்ன கட்டப் போகிறாள்?",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_22890",
    "storyId": "22890-paravaigal-paesum",
    "titleEn": "பறவைகள் பேசும்",
    "titleTa": "பறவைகள் பேசும்",
    "author": "Malarkody",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/527532/size3/d554b58ed4a31df51c45cca2a90e4aa0.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/22890-paravaigal-paesum?mode=read",
    "descriptionEn": "கவனமாக கேட்டுப் பாருங்கள்!  பறவைகள் சொல்வதற்கு நிறைய இருக்கிறது என்பதத் தெரிந்து கொள்வீர்கள்.",
    "descriptionTa": "கவனமாக கேட்டுப் பாருங்கள்!  பறவைகள் சொல்வதற்கு நிறைய இருக்கிறது என்பதத் தெரிந்து கொள்வீர்கள்.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_44632",
    "storyId": "44632-inru-naan",
    "titleEn": "இன்று நான்",
    "titleTa": "இன்று நான்",
    "author": "Sudha  Thilak",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/524542/size3/c273da52c55bd7e5d79cd98401ab3ab2.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/44632-inru-naan?mode=read",
    "descriptionEn": "இன்று மேகா என்னவாக இருப்பாள்? ஆராய்ச்சியாளராகவா விண்வெளி வீரராகவா இசைக் கலைஞராகவா?",
    "descriptionTa": "இன்று மேகா என்னவாக இருப்பாள்? ஆராய்ச்சியாளராகவா விண்வெளி வீரராகவா இசைக் கலைஞராகவா?",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_22887",
    "storyId": "22887-puli-varukirathu-paar",
    "titleEn": "புலி வருகிறது! பார்!",
    "titleTa": "புலி வருகிறது! பார்!",
    "author": "Thilagavathi",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/495589/size3/0ffeaffc8b06617aca654bbe2fa9542b.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/22887-puli-varukirathu-paar?mode=read",
    "descriptionEn": "காட்டில் எல்லா விலங்குகளுக்கும், பறவைகளுக்கும் புலி வருவது தெரிந்து விடும்! புலி பக்கத்தில் உள்ளதைத் தெரிவிக்க அவை எழுப்பும் விதவிதமான எச்சரிக்கை ஒலிகளைக் கேளுங்கள்!",
    "descriptionTa": "காட்டில் எல்லா விலங்குகளுக்கும், பறவைகளுக்கும் புலி வருவது தெரிந்து விடும்! புலி பக்கத்தில் உள்ளதைத் தெரிவிக்க அவை எழுப்பும் விதவிதமான எச்சரிக்கை ஒலிகளைக் கேளுங்கள்!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_50264",
    "storyId": "50264-vilaiyaaduvom-vaanga",
    "titleEn": "விளையாடுவோம் வாங்க",
    "titleTa": "விளையாடுவோம் வாங்க",
    "author": "Saalai Selvam",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/717460/size3/371430b9f5e5718d4be9c13d0336e745.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/50264-vilaiyaaduvom-vaanga?mode=read",
    "descriptionEn": "ரெடி, தயார்...  ஓடு! விளையாட்டின் பின்னால் உள்ள அறிவியலைத் தெரிந்துகொள்!",
    "descriptionTa": "ரெடி, தயார்...  ஓடு! விளையாட்டின் பின்னால் உள்ள அறிவியலைத் தெரிந்துகொள்!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_91602",
    "storyId": "91602-ennaal-uruvakka-mudiyum",
    "titleEn": "என்னால் உருவாக்க முடியும்!",
    "titleTa": "என்னால் உருவாக்க முடியும்!",
    "author": "Praba Ram, Sheela Preuitt",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/709183/size3/68acc59fc68640e3cabffa2a367a7375.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/91602-ennaal-uruvakka-mudiyum?mode=read",
    "descriptionEn": "சிறுவர்களால் பல பொருட்களை உருவாக்க முடியும். அவை என்னென்ன? ‘வளர்வது’ வரிசையின் நான்குப் புத்தகங்களில் இதுவும் ஒன்று.",
    "descriptionTa": "சிறுவர்களால் பல பொருட்களை உருவாக்க முடியும். அவை என்னென்ன? ‘வளர்வது’ வரிசையின் நான்குப் புத்தகங்களில் இதுவும் ஒன்று.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_101374",
    "storyId": "101374-makkum-kuppai-makka-kuppai",
    "titleEn": "மக்கும் குப்பை மக்கா குப்பை",
    "titleTa": "மக்கும் குப்பை மக்கா குப்பை",
    "author": "Nivedha",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/145759/size3/beb14f9fe944bd7f5b8da10710b44755.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/101374-makkum-kuppai-makka-kuppai?mode=read",
    "descriptionEn": "உங்கள் வீடுகளில் குப்பைகளை எவ்வாறு அகற்றுகிறீர்கள்? மக்கும் குப்பைகளையும் மக்காத உலர் குப்பைகளையும் பிரிக்கிறீர்களா?  இந்த வேடிக்கை பாடல் வழி குப்பைகளைப் பிரித்தல் குறித்து அறிவோமா?",
    "descriptionTa": "உங்கள் வீடுகளில் குப்பைகளை எவ்வாறு அகற்றுகிறீர்கள்? மக்கும் குப்பைகளையும் மக்காத உலர் குப்பைகளையும் பிரிக்கிறீர்களா?  இந்த வேடிக்கை பாடல் வழி குப்பைகளைப் பிரித்தல் குறித்து அறிவோமா?",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_59",
    "storyId": "59-susheelaavin-kolangal",
    "titleEn": "சுசீலாவின் கோலங்கள்",
    "titleTa": "சுசீலாவின் கோலங்கள்",
    "author": "Praba Ram, Sheela Preuitt",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/721007/size3/d555da2445138f0ad43899fed6f643b9.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/59-susheelaavin-kolangal?mode=read",
    "descriptionEn": "நீங்கள் வீட்டிலும் பள்ளிகூடங்களிலும் கோலங்களைப் பார்த்திருப்பீர்கள், ஆனால் வானத்தில் கோலத்தைப் பார்த்திருக்கிறீர்களா? படித்துப் பாருங்கள் சுசீலா எப்படி இதை சாதித்தாள் என்று!",
    "descriptionTa": "நீங்கள் வீட்டிலும் பள்ளிகூடங்களிலும் கோலங்களைப் பார்த்திருப்பீர்கள், ஆனால் வானத்தில் கோலத்தைப் பார்த்திருக்கிறீர்களா? படித்துப் பாருங்கள் சுசீலா எப்படி இதை சாதித்தாள் என்று!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_48468",
    "storyId": "48468-gappoovin-nadanam",
    "titleEn": "கப்பூவின் நடனம்",
    "titleTa": "கப்பூவின் நடனம்",
    "author": "Thilagavathi",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/87073/size3/68a0d3d182c04e01576caea671cc33bf.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/48468-gappoovin-nadanam?mode=read",
    "descriptionEn": "‘1 அ’ வகுப்பிலுள்ள அனைவருக்கும் கப்பூவால் ஆட முடியாதெனத் தெரியும். மற்ற மாணவர்கள் இடது கையைத் தூக்கினால், அவள் வலது கையைத் தூக்குகிறாள்! கோமல் மிஸ்ஸால் கப்பூவை நடனமாட வைக்க முடியுமா? நடனத்தின் களிப்பையும், எதிர்ப்பதங்களையும் குறித்த ஒரு கதை.",
    "descriptionTa": "‘1 அ’ வகுப்பிலுள்ள அனைவருக்கும் கப்பூவால் ஆட முடியாதெனத் தெரியும். மற்ற மாணவர்கள் இடது கையைத் தூக்கினால், அவள் வலது கையைத் தூக்குகிறாள்! கோமல் மிஸ்ஸால் கப்பூவை நடனமாட வைக்க முடியுமா? நடனத்தின் களிப்பையும், எதிர்ப்பதங்களையும் குறித்த ஒரு கதை.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38359",
    "storyId": "38359-tambuvin-pattam",
    "titleEn": "தம்புவின் பட்டம்",
    "titleTa": "தம்புவின் பட்டம்",
    "author": "Mythily Thevaraja",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/99489/size3/66d351634df9686be04f403a2a0375f2.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38359-tambuvin-pattam?mode=read",
    "descriptionEn": "தம்புவுக்கு பட்டம் ஏற்றுவது என்றால் சரியான விருப்பம். ஒருநாள் தம்பு ஏற்றிய பட்டம் அறுந்து விட்டது. தம்பு பட்டத்தைப் பிடிக்க ஓடினான். தம்பு தன்னுடைய பட்டத்தினைப் பிடித்தானா...?",
    "descriptionTa": "தம்புவுக்கு பட்டம் ஏற்றுவது என்றால் சரியான விருப்பம். ஒருநாள் தம்பு ஏற்றிய பட்டம் அறுந்து விட்டது. தம்பு பட்டத்தைப் பிடிக்க ஓடினான். தம்பு தன்னுடைய பட்டத்தினைப் பிடித்தானா...?",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_47925",
    "storyId": "47925-ethirum-pudhirum",
    "titleEn": "எதிரும் புதிரும்",
    "titleTa": "எதிரும் புதிரும்",
    "author": "Sudha  Thilak",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/714299/size3/a1ba8666ed08595b45d6d54a0a225994.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/47925-ethirum-pudhirum?mode=read",
    "descriptionEn": "இயற்கையின் ரகசியங்களைக் காண வெகுதூரம் போக வேண்டியதில்லை. அவை உங்கள் வீட்டுப் பக்கத்திலிருக்கும் பூங்காவிலேயே இருக்கின்றன. இயற்கை காட்டும் நேரெதிர்களை இப்புத்தகத்தில் அறியலாம், வாருங்கள்!",
    "descriptionTa": "இயற்கையின் ரகசியங்களைக் காண வெகுதூரம் போக வேண்டியதில்லை. அவை உங்கள் வீட்டுப் பக்கத்திலிருக்கும் பூங்காவிலேயே இருக்கின்றன. இயற்கை காட்டும் நேரெதிர்களை இப்புத்தகத்தில் அறியலாம், வாருங்கள்!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_24873",
    "storyId": "24873-unavu-arakkan",
    "titleEn": "உணவு அரக்கன்",
    "titleTa": "உணவு அரக்கன்",
    "author": "Rajam Anand",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/123549/size3/3687d0df50d079218bf3867d505dcd51.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/24873-unavu-arakkan?mode=read",
    "descriptionEn": "சப்பாத்தி முதல் தோசை வரை மற்றும் முறுக்கு முதல் பர்ஃபி வரை விதவிதமான உணவு வகைகளை இந்தியா முழுவதும் நீங்கள் கண்டும் சுவைத்தும் இருக்கலாம். ஆனால், அவற்றின் வடிவம் குறித்து எப்போதாவது யோசித்தது உண்டா?",
    "descriptionTa": "சப்பாத்தி முதல் தோசை வரை மற்றும் முறுக்கு முதல் பர்ஃபி வரை விதவிதமான உணவு வகைகளை இந்தியா முழுவதும் நீங்கள் கண்டும் சுவைத்தும் இருக்கலாம். ஆனால், அவற்றின் வடிவம் குறித்து எப்போதாவது யோசித்தது உண்டா?",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_22930",
    "storyId": "22930-avai-ellaam-yaar-saappitadu",
    "titleEn": "அவை எல்லாம் யார் சாப்பிட்டது?",
    "titleTa": "அவை எல்லாம் யார் சாப்பிட்டது?",
    "author": "Anitha Ramkumar",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/188968/size3/715cc0ac513fbf98008ab8be6fa089d2.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/22930-avai-ellaam-yaar-saappitadu?mode=read",
    "descriptionEn": "காடுகள் எப்படி இவ்வளவு சுத்தமாக இருக்கின்றன? காடுகளில் எப்படி எதுவும் வீணாகப் போவதில்லை என்று தெரிந்து கொள்ளலாமா?",
    "descriptionTa": "காடுகள் எப்படி இவ்வளவு சுத்தமாக இருக்கின்றன? காடுகளில் எப்படி எதுவும் வீணாகப் போவதில்லை என்று தெரிந்து கொள்ளலாமா?",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_881",
    "storyId": "881-oruvelai",
    "titleEn": "ஒருவேளை…",
    "titleTa": "ஒருவேளை…",
    "author": "N. Chokkan",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/723050/size3/9093d145b12c1371d8ae9d976bfeb4ca.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/881-oruvelai?mode=read",
    "descriptionEn": "ஷ்யாமுக்குக் காலையில் எழுந்து பள்ளிக்குச் செல்வதே பிடிக்காது. ஒருநாள், அவன் ஒரு கற்பனை உலகில் மூழ்குகிறான், அதன்மூலம் பள்ளியையும் வீட்டையும் ரொம்ப ஜாலியாக மாற்றிவிடுகிறான்!",
    "descriptionTa": "ஷ்யாமுக்குக் காலையில் எழுந்து பள்ளிக்குச் செல்வதே பிடிக்காது. ஒருநாள், அவன் ஒரு கற்பனை உலகில் மூழ்குகிறான், அதன்மூலம் பள்ளியையும் வீட்டையும் ரொம்ப ஜாலியாக மாற்றிவிடுகிறான்!",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_48448",
    "storyId": "48448-monavukku-pidiththa-chappathi",
    "titleEn": "மோனாவுக்குப் பிடித்த சப்பாத்தி",
    "titleTa": "மோனாவுக்குப் பிடித்த சப்பாத்தி",
    "author": "Violet வயலட்",
    "level": "1",
    "levelLabelEn": "Level 1 (Emergent)",
    "levelLabelTa": "நிலை 1 (தொடக்க நிலை)",
    "targetGrades": "KG, Year 1",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/83282/size3/6f439dc6767b16a5454d590c58cecae7.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/48448-monavukku-pidiththa-chappathi?mode=read",
    "descriptionEn": "நன்கு உப்பிய, சூடான சப்பாத்தி எப்படி செய்யப்படுகிறது? மோனாவோடு சேர்ந்து நீங்களும் தெரிந்துகொள்ளுங்கள்.",
    "descriptionTa": "நன்கு உப்பிய, சூடான சப்பாத்தி எப்படி செய்யப்படுகிறது? மோனாவோடு சேர்ந்து நீங்களும் தெரிந்துகொள்ளுங்கள்.",
    "readingPoints": 50,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_879",
    "storyId": "879-eli-eli",
    "titleEn": "எலி! எலி!",
    "titleTa": "எலி! எலி!",
    "author": "N. Chokkan",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/699239/size3/64aac1468dabc0be40ef455f26448dd6.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/879-eli-eli?mode=read",
    "descriptionEn": "ஒரு வீட்டில் எலி புகுந்துவிடுகிறது. அவ்வளவுதான், வீடே தலைகீழாகத் திருப்பிப்போடப்பட்டு ஒரே களேபரம். அதன்பிறகு என்ன நடந்தது? பரபரப்பான இந்தக் கதையைச் சிறு குழந்தைகள் கும்மாளம் போட்டு ரசிப்பார்கள்!",
    "descriptionTa": "ஒரு வீட்டில் எலி புகுந்துவிடுகிறது. அவ்வளவுதான், வீடே தலைகீழாகத் திருப்பிப்போடப்பட்டு ஒரே களேபரம். அதன்பிறகு என்ன நடந்தது? பரபரப்பான இந்தக் கதையைச் சிறு குழந்தைகள் கும்மாளம் போட்டு ரசிப்பார்கள்!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_2169",
    "storyId": "2169-thuppariyum-durai",
    "titleEn": "துப்பறியும் துரை",
    "titleTa": "துப்பறியும் துரை",
    "author": "N. Chokkan",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/721717/size3/eb5a572c2dc1b8583ea321e7209afa20.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/2169-thuppariyum-durai?mode=read",
    "descriptionEn": "துரைக்கு எதையாவது துப்பறிய ஆசை. பூதக்கண்ணாடியை எடுத்துக்கொண்டு காட்டுக்குள் நுழைகிறான். அங்கே அவனுக்கு ஒரு புதிய சிநேகிதி கிடைக்கிறாள். அதன்பிறகு என்ன நடந்தது? இந்தக் கதையைப் படித்தால் தெரியும்!",
    "descriptionTa": "துரைக்கு எதையாவது துப்பறிய ஆசை. பூதக்கண்ணாடியை எடுத்துக்கொண்டு காட்டுக்குள் நுழைகிறான். அங்கே அவனுக்கு ஒரு புதிய சிநேகிதி கிடைக்கிறாள். அதன்பிறகு என்ன நடந்தது? இந்தக் கதையைப் படித்தால் தெரியும்!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38669",
    "storyId": "38669-cuvaiyana-camaiyal",
    "titleEn": "சுவையான சமையல்",
    "titleTa": "சுவையான சமையல்",
    "author": "Chammi Iresha",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/105036/size3/18f8fd4a121fc54acd71d658d4013da8.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38669-cuvaiyana-camaiyal?mode=read",
    "descriptionEn": "ஒரே வேலையினை மீண்டும் மீண்டும் செய்தால் உங்களுக்கு பிடிக்குமா..? பிடிக்காமல் போகும் இல்லையா...?\r\nகொஞ்சம் வித்தியாசமாக யோசித்தால் விருப்பத்தோடு செய்யலாம். இந்தக் கதையில் வருகின்ற முயலாரும் வித்தியாசமாக யோசித்தார். என்ன செய்திருப்பார் முயலார்?",
    "descriptionTa": "ஒரே வேலையினை மீண்டும் மீண்டும் செய்தால் உங்களுக்கு பிடிக்குமா..? பிடிக்காமல் போகும் இல்லையா...?\r\nகொஞ்சம் வித்தியாசமாக யோசித்தால் விருப்பத்தோடு செய்யலாம். இந்தக் கதையில் வருகின்ற முயலாரும் வித்தியாசமாக யோசித்தார். என்ன செய்திருப்பார் முயலார்?",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_34899",
    "storyId": "34899-vaanavil-saambaar",
    "titleEn": "வானவில் சாம்பார்",
    "titleTa": "வானவில் சாம்பார்",
    "author": "Rajam Anand",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/56684/size3/b9155fef4902fd82e8b9529dcf1c6ce3.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/34899-vaanavil-saambaar?mode=read",
    "descriptionEn": "பாட்டியும், பவ்யாவும் இன்று மதிய உணவிற்கு என்ன சாப்பிடப் போகிறார்கள்? வேறென்ன? பவ்யாவிற்குப் பிடித்த வானவில் சாம்பார்தான்! அவர்களின் வண்ணமயமான சமையலை நீங்களும் ரசித்து மகிழுங்கள்.",
    "descriptionTa": "பாட்டியும், பவ்யாவும் இன்று மதிய உணவிற்கு என்ன சாப்பிடப் போகிறார்கள்? வேறென்ன? பவ்யாவிற்குப் பிடித்த வானவில் சாம்பார்தான்! அவர்களின் வண்ணமயமான சமையலை நீங்களும் ரசித்து மகிழுங்கள்.",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38477",
    "storyId": "38477-aamaiyum-kurangum",
    "titleEn": "ஆமையும் குரங்கும்",
    "titleTa": "ஆமையும் குரங்கும்",
    "author": "Prashaanth Ramalingam",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/99490/size3/e2715bcf5031ec91fb9ba75192bd6cba.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38477-aamaiyum-kurangum?mode=read",
    "descriptionEn": "ஆமைகள் எப்படி விளாம்பழக் கோதுகளை உடைத்தன? ",
    "descriptionTa": "ஆமைகள் எப்படி விளாம்பழக் கோதுகளை உடைத்தன? ",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38644",
    "storyId": "38644-oor-vittu-oor",
    "titleEn": "ஊர் விட்டு ஊர்",
    "titleTa": "ஊர் விட்டு ஊர்",
    "author": "Anitha Ramkumar",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/527558/size3/d2ca9b60f3812f6cfe8931703ea209ee.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38644-oor-vittu-oor?mode=read",
    "descriptionEn": "நீனாவும் அவள் குடும்பமும் கொல்கத்தாவிலிருந்து தில்லிக்கு இடம்பெயர்கிறார்கள். நீனாவிற்கு அது பிடிக்கவே இல்லை. இரயில் பயணத்தின் பொழுது அவள் பெற்றோரால் அவளை உற்சாகப்படுத்த முடிந்ததா?",
    "descriptionTa": "நீனாவும் அவள் குடும்பமும் கொல்கத்தாவிலிருந்து தில்லிக்கு இடம்பெயர்கிறார்கள். நீனாவிற்கு அது பிடிக்கவே இல்லை. இரயில் பயணத்தின் பொழுது அவள் பெற்றோரால் அவளை உற்சாகப்படுத்த முடிந்ததா?",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_24881",
    "storyId": "24881-umaavum-uppumaavum",
    "titleEn": "உமாவும், உப்புமாவும்",
    "titleTa": "உமாவும், உப்புமாவும்",
    "author": "Uma Sekhar",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/91617/size3/7665b5719e56df1b97c01a18608f9f09.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/24881-umaavum-uppumaavum?mode=read",
    "descriptionEn": "உமா,  காலைச் சிற்றுண்டியை ஒருபோதும் சாப்பிட மாட்டாள். அதற்கு பதிலாக அதோடு விளையாடுவாள். அவள் சாப்பாட்டுடன் விளையாடுவதைத் தடுக்க ஏதேனும் வழி இருக்கிறதா?",
    "descriptionTa": "உமா,  காலைச் சிற்றுண்டியை ஒருபோதும் சாப்பிட மாட்டாள். அதற்கு பதிலாக அதோடு விளையாடுவாள். அவள் சாப்பாட்டுடன் விளையாடுவதைத் தடுக்க ஏதேனும் வழி இருக்கிறதா?",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38722",
    "storyId": "38722-where-is-my-mother",
    "titleEn": "கீச்....கீச்...",
    "titleTa": "கீச்....கீச்...",
    "author": "Hemalatha Kanagalingam",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/128583/size3/c7cc6b50e502c26ed6dc910456cb202c.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38722-where-is-my-mother?mode=read",
    "descriptionEn": "சின்னப் பறவை தாயைக் காணத் தவிக்கின்றது. எதிர்ப்படும் அனைவரிடமும் நீங்களா என் தாய்..?' என விசாரிக்கின்றது.\r\n முடிவில் தாயைக் கண்டுகொள்கின்றது. சின்னப் பறவை தாயைக் காண என்ன செய்தது?",
    "descriptionTa": "சின்னப் பறவை தாயைக் காணத் தவிக்கின்றது. எதிர்ப்படும் அனைவரிடமும் நீங்களா என் தாய்..?' என விசாரிக்கின்றது.\r\n முடிவில் தாயைக் கண்டுகொள்கின்றது. சின்னப் பறவை தாயைக் காண என்ன செய்தது?",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_951",
    "storyId": "951-rombba-sattum",
    "titleEn": "ரொம்ப சத்தம்",
    "titleTa": "ரொம்ப சத்தம்",
    "author": "S. Jayaraman",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/703953/size3/788a320045339daf95e6616b6a80dd8e.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/951-rombba-sattum?mode=read",
    "descriptionEn": "சிருங்கேரி சீனிவாசன் நீண்ட தலைமுடியுள்ள அன்பான விவசாயி. அவர் ஒரு புதிய நெடுஞ்சாலை வழியாக தன் பசுக்களை சந்தைக்கு அழைத்துச் செல்லவேண்டியிருந்தது. சாலையில் சத்தம் மிகவும் அதிகமாக இருந்தது. இதனைச் சமாளிக்க அவர் புத்திசாலித்தனமான ஒரு வழியைக் கண்டுபிடிக்கிறார். எப்பொழுதும் போல!",
    "descriptionTa": "சிருங்கேரி சீனிவாசன் நீண்ட தலைமுடியுள்ள அன்பான விவசாயி. அவர் ஒரு புதிய நெடுஞ்சாலை வழியாக தன் பசுக்களை சந்தைக்கு அழைத்துச் செல்லவேண்டியிருந்தது. சாலையில் சத்தம் மிகவும் அதிகமாக இருந்தது. இதனைச் சமாளிக்க அவர் புத்திசாலித்தனமான ஒரு வழியைக் கண்டுபிடிக்கிறார். எப்பொழுதும் போல!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_57289",
    "storyId": "57289-vaalizhantha-panri-kutti",
    "titleEn": "வாலிழந்த பன்றிக் குட்டி",
    "titleTa": "வாலிழந்த பன்றிக் குட்டி",
    "author": "Anitha Ramkumar",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/120979/size3/3d623966446a7444473bbd5c84c8ba2e.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/57289-vaalizhantha-panri-kutti?mode=read",
    "descriptionEn": "பன்றிக் குட்டியான பொங்கலுக்கு ஒரு சிறிய சிக்கல்! பரபரப்பான சாகசங்களைத் தேடி அவளுடைய வால் மட்டும் அடிக்கடி அவளை விட்டுவிட்டு ஓடிப்போய்விடுகிறது! ஒளிந்திருப்பதைக் கண்டுபிடிக்கும் இந்தப் புத்தகத்தில் தன் ஓடிப்போன வாலைக் கண்டுபிடிக்க பொங்கலுக்கு உதவுங்களேன்!",
    "descriptionTa": "பன்றிக் குட்டியான பொங்கலுக்கு ஒரு சிறிய சிக்கல்! பரபரப்பான சாகசங்களைத் தேடி அவளுடைய வால் மட்டும் அடிக்கடி அவளை விட்டுவிட்டு ஓடிப்போய்விடுகிறது! ஒளிந்திருப்பதைக் கண்டுபிடிக்கும் இந்தப் புத்தகத்தில் தன் ஓடிப்போன வாலைக் கண்டுபிடிக்க பொங்கலுக்கு உதவுங்களேன்!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_10932",
    "storyId": "10932-ammachiyin-adhisaya-iyanthirangal",
    "titleEn": "அம்மாச்சியின் அதிசய இயந்திரங்கள்",
    "titleTa": "அம்மாச்சியின் அதிசய இயந்திரங்கள்",
    "author": "S Krishnan",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/712718/size3/9afb2c00f7a211ff4c8699e66ca7db0b.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/10932-ammachiyin-adhisaya-iyanthirangal?mode=read",
    "descriptionEn": "சூரஜும் அவன் அம்மாச்சியும் புதிது புதிதாக ஏதேனும் கண்டுபிடிப்பதை விரும்புகிறவர்கள்! ஒருநாள், எளிய இயந்திரங்களைக் கொண்டு அவர்கள் தேங்காய் பர்பி செய்தார்கள். அந்தச் சாகசத்தில் நீங்களும் இணையுங்கள்.\r\n",
    "descriptionTa": "சூரஜும் அவன் அம்மாச்சியும் புதிது புதிதாக ஏதேனும் கண்டுபிடிப்பதை விரும்புகிறவர்கள்! ஒருநாள், எளிய இயந்திரங்களைக் கொண்டு அவர்கள் தேங்காய் பர்பி செய்தார்கள். அந்தச் சாகசத்தில் நீங்களும் இணையுங்கள்.\r\n",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_11834",
    "storyId": "11834-sathya-gavanam",
    "titleEn": "சத்யா, கவனம்!",
    "titleTa": "சத்யா, கவனம்!",
    "author": "S Krishnan",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/724002/size3/2ec570b512dfcbf96a9b0bea170cb39b.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/11834-sathya-gavanam?mode=read",
    "descriptionEn": "சத்யா தன் அம்மா வேலை செய்யும் பண்ணைக்கு உடன் செல்லும்போது அவனோடு நீங்களும் குதித்தும் ஓடியும் தாவியும் ஏறியும் செல்லுங்கள். கூடவே, நாம் நகர்வதற்குப் பயன்படுத்தும் வித்யாசமான அற்புதமான வழிமுறைகளையும் தெரிந்துகொள்ளுங்கள்.\r\n\r\n",
    "descriptionTa": "சத்யா தன் அம்மா வேலை செய்யும் பண்ணைக்கு உடன் செல்லும்போது அவனோடு நீங்களும் குதித்தும் ஓடியும் தாவியும் ஏறியும் செல்லுங்கள். கூடவே, நாம் நகர்வதற்குப் பயன்படுத்தும் வித்யாசமான அற்புதமான வழிமுறைகளையும் தெரிந்துகொள்ளுங்கள்.\r\n\r\n",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_304",
    "storyId": "304-appaavin-meesai",
    "titleEn": "அப்பாவின் மீசை",
    "titleTa": "அப்பாவின் மீசை",
    "author": "Praba Ram, Sheela Preuitt",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/721686/size3/0eaa2e9b2d4d4c465ba2c5e05a6f092c.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/304-appaavin-meesai?mode=read",
    "descriptionEn": "அனுவிற்கு தன் தந்தையைப் பற்றி மிகவும் பிடித்தது என்ன? அவரது மீசை! மீசையுள்ளவர்கள் அனைவரையும் அனுவிற்குப் பிடிக்கும்! மீசையை பார்க்கும்போதெல்லாம் அனுவிற்கு வேடிக்கையான எண்ணங்கள் பிறக்கும்!",
    "descriptionTa": "அனுவிற்கு தன் தந்தையைப் பற்றி மிகவும் பிடித்தது என்ன? அவரது மீசை! மீசையுள்ளவர்கள் அனைவரையும் அனுவிற்குப் பிடிக்கும்! மீசையை பார்க்கும்போதெல்லாம் அனுவிற்கு வேடிக்கையான எண்ணங்கள் பிறக்கும்!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_14779",
    "storyId": "14779-kurumbukkaara-pambaram",
    "titleEn": "குறும்புக்கார பம்பரம்",
    "titleTa": "குறும்புக்கார பம்பரம்",
    "author": "N. Chokkan",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/722862/size3/6f38839522e2b7cb345f55e6c3d29b60.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/14779-kurumbukkaara-pambaram?mode=read",
    "descriptionEn": "இந்தக் குறும்பு பம்பரம் ஊரெங்கும் சென்று விளையாட்டுக் காட்டுகிறது!\r\nவாருங்கள், நாமும் அதோடு சுற்றி வருவோம்.",
    "descriptionTa": "இந்தக் குறும்பு பம்பரம் ஊரெங்கும் சென்று விளையாட்டுக் காட்டுகிறது!\r\nவாருங்கள், நாமும் அதோடு சுற்றி வருவோம்.",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_44652",
    "storyId": "44652-aththaiyum-naanum",
    "titleEn": "அத்தையும் நானும்",
    "titleTa": "அத்தையும் நானும்",
    "author": "S. Jayaraman",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/117615/size3/2b5f77b28bb196dfb73d2b136890b5b0.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/44652-aththaiyum-naanum?mode=read",
    "descriptionEn": "சுட்கு தனது அத்தையுடன் நடை போய்விட்டு வருகிறான். அவனது பைகளில் பல அரிய செல்வங்களும் அவற்றைப் பற்றிய கதைகளும் நிறைந்திருக்கிறன. ஒரு குழந்தையின் பார்வையில் கூறப்பட்ட, அத்தைக்கும் மருமகனுக்கும் இடையிலான அழகிய உறவைப் பற்றிய கதை இது.",
    "descriptionTa": "சுட்கு தனது அத்தையுடன் நடை போய்விட்டு வருகிறான். அவனது பைகளில் பல அரிய செல்வங்களும் அவற்றைப் பற்றிய கதைகளும் நிறைந்திருக்கிறன. ஒரு குழந்தையின் பார்வையில் கூறப்பட்ட, அத்தைக்கும் மருமகனுக்கும் இடையிலான அழகிய உறவைப் பற்றிய கதை இது.",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_45086",
    "storyId": "45086-meeravum-ameeravum",
    "titleEn": "மீராவும் அமீராவும்",
    "titleTa": "மீராவும் அமீராவும்",
    "author": "Elavasa  Kothanar",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/117617/size3/835e1d375a9f1cb096053b2a8491e360.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/45086-meeravum-ameeravum?mode=read",
    "descriptionEn": "அமீரா மீராவின் உயிர்த் தோழி. ஆனால் மற்றவர்கள் யாரும் அவளைப் பார்க்க முடியாது. ஏனென்றால் அமீரா ஒரு கற்பனை முள்ளம்பன்றி. இந்த இரு நண்பர்களின் நிஜமும் கற்பனையும் கலந்த பல்வேறு சாகசங்களைக் காணலாம், வாருங்கள்.",
    "descriptionTa": "அமீரா மீராவின் உயிர்த் தோழி. ஆனால் மற்றவர்கள் யாரும் அவளைப் பார்க்க முடியாது. ஏனென்றால் அமீரா ஒரு கற்பனை முள்ளம்பன்றி. இந்த இரு நண்பர்களின் நிஜமும் கற்பனையும் கலந்த பல்வேறு சாகசங்களைக் காணலாம், வாருங்கள்.",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_11891",
    "storyId": "11891-neema-indru-enna-saapidukiraal",
    "titleEn": "நீமா இன்று என்ன சாப்பிடுகிறாள்?",
    "titleTa": "நீமா இன்று என்ன சாப்பிடுகிறாள்?",
    "author": "Praba Ram, Sheela Preuitt",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/712721/size3/2f46f2aea0d54ba83cce96e1c6f9d5d9.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/11891-neema-indru-enna-saapidukiraal?mode=read",
    "descriptionEn": "சாப்பிடுவதை நேசிக்கும் நீமாவைச்  சந்தியுங்கள். வழுக்கும் லிச்சிபழம், அமுக்கினால் பிதுங்கும் பழுத்த நாவற்பழம், புளிப்பான புளியங்காய், பச்சைப் பசேல் கீரை எல்லாமே நீமாவுக்குப் பிடித்தமானவை. ஆண்டு முழுவதும் நீமா என்னவெல்லாம் மென்று  கடித்து தின்கிறாள் என்று பாருங்கள்! \r\n\r\n",
    "descriptionTa": "சாப்பிடுவதை நேசிக்கும் நீமாவைச்  சந்தியுங்கள். வழுக்கும் லிச்சிபழம், அமுக்கினால் பிதுங்கும் பழுத்த நாவற்பழம், புளிப்பான புளியங்காய், பச்சைப் பசேல் கீரை எல்லாமே நீமாவுக்குப் பிடித்தமானவை. ஆண்டு முழுவதும் நீமா என்னவெல்லாம் மென்று  கடித்து தின்கிறாள் என்று பாருங்கள்! \r\n\r\n",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_51700",
    "storyId": "51700-enna-nadakkum",
    "titleEn": "என்ன நடக்கும்?",
    "titleTa": "என்ன நடக்கும்?",
    "author": "Vishal Raja",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/726929/size3/15b2e1748d152812ed5526070aca52ef.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/51700-enna-nadakkum?mode=read",
    "descriptionEn": "சுனிதா தன் தொப்புளை அழுத்தினாலோ காதுகளைப் பிடித்து இழுத்தாலோ என்ன நடக்கும்? கற்பனையின் ஆற்றல் பற்றிய இக்கதை, உடலின் வெவ்வேறு பாகங்களை குழந்தைகளுக்கு அறிமுகமும் செய்கிறது.",
    "descriptionTa": "சுனிதா தன் தொப்புளை அழுத்தினாலோ காதுகளைப் பிடித்து இழுத்தாலோ என்ன நடக்கும்? கற்பனையின் ஆற்றல் பற்றிய இக்கதை, உடலின் வெவ்வேறு பாகங்களை குழந்தைகளுக்கு அறிமுகமும் செய்கிறது.",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_44007",
    "storyId": "44007-vidumurai",
    "titleEn": "விடுமுறை",
    "titleTa": "விடுமுறை",
    "author": "Rajam Anand",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/117606/size3/35ff17c7689f09ce05ef74d41c9ff7b7.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/44007-vidumurai?mode=read",
    "descriptionEn": " விடுமுறைகள் விலைமதிப்பற்றவை! முடிவுறாத விடுமுறைகளைப் பற்றிய வேடிக்கைக் கதையொன்றை அழகான பாடலின் வடிவில் உரக்கப் படிக்கலாம் வாருங்கள்!",
    "descriptionTa": " விடுமுறைகள் விலைமதிப்பற்றவை! முடிவுறாத விடுமுறைகளைப் பற்றிய வேடிக்கைக் கதையொன்றை அழகான பாடலின் வடிவில் உரக்கப் படிக்கலாம் வாருங்கள்!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_26049",
    "storyId": "26049-kandupidi-paarppom",
    "titleEn": "கண்டுபிடி பார்ப்போம்!",
    "titleTa": "கண்டுபிடி பார்ப்போம்!",
    "author": "Anitha Ramkumar",
    "level": "2",
    "levelLabelEn": "Level 2 (Growing)",
    "levelLabelTa": "நிலை 2 (இரண்டாம் நிலை)",
    "targetGrades": "Year 2, Year 3",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/116826/size3/426af0a182efe12d8719ad2b2404bdee.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/26049-kandupidi-paarppom?mode=read",
    "descriptionEn": "உலகத்திலேயே, கண்ணாமூச்சி ஆட்டத்தில் மியாதான் மிகச் சிறந்தவள். உன்னால் அவளைக் கண்டுபிடிக்க முடியுமா? ஒளிந்து விளையாடும் மியாவையும் அவள் அம்மாவின் பட்டியலில் இருக்கும் பொருட்களையும் இப்புத்தகத்தில் கண்டுபிடி பார்ப்போம்!",
    "descriptionTa": "உலகத்திலேயே, கண்ணாமூச்சி ஆட்டத்தில் மியாதான் மிகச் சிறந்தவள். உன்னால் அவளைக் கண்டுபிடிக்க முடியுமா? ஒளிந்து விளையாடும் மியாவையும் அவள் அம்மாவின் பட்டியலில் இருக்கும் பொருட்களையும் இப்புத்தகத்தில் கண்டுபிடி பார்ப்போம்!",
    "readingPoints": 60,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_989",
    "storyId": "989-tok-tok",
    "titleEn": "டொக் டொக்!",
    "titleTa": "டொக் டொக்!",
    "author": "N. Chokkan",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/706157/size3/93c759f49808e92b7f9cefb99d3989f4.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/989-tok-tok?mode=read",
    "descriptionEn": "இரவு நேரம். ஆனால், சோனாப்பூர் ராஜாவால் தூங்கமுடியவில்லை. காரணம், எங்கிருந்தோ வருகிற மர்மச் சத்தம்தான்!என்ன  ஆயிற்று? ராஜா தூங்கினாரா இல்லையா? இந்தக் கதையைப் படித்துத் தெரிந்துகொள்ளுங்கள்.",
    "descriptionTa": "இரவு நேரம். ஆனால், சோனாப்பூர் ராஜாவால் தூங்கமுடியவில்லை. காரணம், எங்கிருந்தோ வருகிற மர்மச் சத்தம்தான்!என்ன  ஆயிற்று? ராஜா தூங்கினாரா இல்லையா? இந்தக் கதையைப் படித்துத் தெரிந்துகொள்ளுங்கள்.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_15082",
    "storyId": "15082-akka-akka-idi-yengirunthu-varuthu",
    "titleEn": "அக்கா! அக்கா! இடி எங்கிருந்து வருது?",
    "titleTa": "அக்கா! அக்கா! இடி எங்கிருந்து வருது?",
    "author": "S. Jayaraman",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/722406/size3/9d3e085a533c4c69c41f353bbdbd072d.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/15082-akka-akka-idi-yengirunthu-varuthu?mode=read",
    "descriptionEn": "சின்ன தம்பியின் விஷயதாகம் நிரம்பிய மனதில் எப்பொழுதும் பெரிய அக்காவிடம் கேட்பதற்காக நிறைய கேள்விகள் இருக்கும். \r\nஅக்காவிடம் எல்லா கேள்விகளுக்கும் சரியான பதில் இருக்கும் என்பதும் தம்பிக்கு தெரியும். \r\nஏனென்றால் அக்காதான் எப்பொழுதும் பெரிய பெரிய  புத்தகங்களாக படிக்கிறாரே!இந்த புத்தகத்தில் சின்ன தம்பிக்கு இடிமுழக்கம் எங்கிருந்து வருகிறது என்று சந்தேகம். \r\nசொர்க்கத்தையே நடுங்கவைக்கும் வண்ணம் வானத்தில் வாழும் கோபம் கொண்ட அரக்கனின் கர்ஜனைதான் இடிமுழக்கமோ என்பதில் தொடங்கி, \r\nஅட்டகாசம் புரியும் பைக் வீரர்கள் மேகத்தில் கூடி செய்யும் சப்தம்தான் இடியோ என்று பலவித பதில்கள்.கடைசியில் அக்கா சரியான விடையை சொல்கிறார். \r\nகுதூகலமூட்டும் இந்த புத்தகத்தை படித்து விடையை தெரிந்து கொள்ளும்முன் நீங்களே சொல்லுங்கள்: இடிமுழக்கம் எங்கிருந்து வருகிறது?\r\n\r\n",
    "descriptionTa": "சின்ன தம்பியின் விஷயதாகம் நிரம்பிய மனதில் எப்பொழுதும் பெரிய அக்காவிடம் கேட்பதற்காக நிறைய கேள்விகள் இருக்கும். \r\nஅக்காவிடம் எல்லா கேள்விகளுக்கும் சரியான பதில் இருக்கும் என்பதும் தம்பிக்கு தெரியும். \r\nஏனென்றால் அக்காதான் எப்பொழுதும் பெரிய பெரிய  புத்தகங்களாக படிக்கிறாரே!இந்த புத்தகத்தில் சின்ன தம்பிக்கு இடிமுழக்கம் எங்கிருந்து வருகிறது என்று சந்தேகம். \r\nசொர்க்கத்தையே நடுங்கவைக்கும் வண்ணம் வானத்தில் வாழும் கோபம் கொண்ட அரக்கனின் கர்ஜனைதான் இடிமுழக்கமோ என்பதில் தொடங்கி, \r\nஅட்டகாசம் புரியும் பைக் வீரர்கள் மேகத்தில் கூடி செய்யும் சப்தம்தான் இடியோ என்று பலவித பதில்கள்.கடைசியில் அக்கா சரியான விடையை சொல்கிறார். \r\nகுதூகலமூட்டும் இந்த புத்தகத்தை படித்து விடையை தெரிந்து கொள்ளும்முன் நீங்களே சொல்லுங்கள்: இடிமுழக்கம் எங்கிருந்து வருகிறது?\r\n\r\n",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_681",
    "storyId": "681-pallikku-vanda-kaaigarigal",
    "titleEn": "பள்ளிக்கு வந்த காய்கறிகள்",
    "titleTa": "பள்ளிக்கு வந்த காய்கறிகள்",
    "author": "S. Jayaraman",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/722318/size3/17abcfb72df4343564c63356594732e8.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/681-pallikku-vanda-kaaigarigal?mode=read",
    "descriptionEn": "ராஜுவுக்கு தன் கண்களையே நம்ப முடியவில்லை. பள்ளிக்குச் செல்லும் வழியில் விதவிதமான வடிவங்களில் காய்கறிகள், பள்ளிக்கூடப் பைகள் மற்றும் தண்ணீர் பாட்டில்களுடன் பள்ளி நோக்கிச் செல்வதைக் காண்கிறான். அதுமட்டுமா! அவன் ஆசிரியை உட்பட யாருக்குமே இதை பார்த்து ஆச்சரியமாக இல்லை. என்னதான் நடக்கிறது இங்கே?\r\n",
    "descriptionTa": "ராஜுவுக்கு தன் கண்களையே நம்ப முடியவில்லை. பள்ளிக்குச் செல்லும் வழியில் விதவிதமான வடிவங்களில் காய்கறிகள், பள்ளிக்கூடப் பைகள் மற்றும் தண்ணீர் பாட்டில்களுடன் பள்ளி நோக்கிச் செல்வதைக் காண்கிறான். அதுமட்டுமா! அவன் ஆசிரியை உட்பட யாருக்குமே இதை பார்த்து ஆச்சரியமாக இல்லை. என்னதான் நடக்கிறது இங்கே?\r\n",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_11879",
    "storyId": "11879-punnagaikum-pattampoochi",
    "titleEn": "புன்னகைக்கும் பட்டாம்பூச்சி!",
    "titleTa": "புன்னகைக்கும் பட்டாம்பூச்சி!",
    "author": "N. Chokkan",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/712825/size3/46977bed0760c446c9dd926ee5c83ee5.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/11879-punnagaikum-pattampoochi?mode=read",
    "descriptionEn": "காவ்யாவின் குடும்பம் கிராமத்திலிருந்து பெங்களூருக்குக் குடிபெயர்கிறது. அவள் புதிதாக சேர்ந்திருக்கும் பள்ளியில் அவளுக்குத் தோழிகள் யாருமே இல்லை. ஒருநாள், அவள் பட்டாம்பூச்சிப் பூங்காவுக்குச் செல்கிறாள், பட்டாம்பூச்சிகளுடன் தனக்கிருக்கும் சிறப்புப் பிணைப்பைப் புரிந்துகொள்கிறாள், அங்கே அவளுக்கொரு புதிய தோழியும் கிடைக்கிறாள்.\r\n\r\n",
    "descriptionTa": "காவ்யாவின் குடும்பம் கிராமத்திலிருந்து பெங்களூருக்குக் குடிபெயர்கிறது. அவள் புதிதாக சேர்ந்திருக்கும் பள்ளியில் அவளுக்குத் தோழிகள் யாருமே இல்லை. ஒருநாள், அவள் பட்டாம்பூச்சிப் பூங்காவுக்குச் செல்கிறாள், பட்டாம்பூச்சிகளுடன் தனக்கிருக்கும் சிறப்புப் பிணைப்பைப் புரிந்துகொள்கிறாள், அங்கே அவளுக்கொரு புதிய தோழியும் கிடைக்கிறாள்.\r\n\r\n",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_34900",
    "storyId": "34900-enna-samaiyal",
    "titleEn": "என்ன சமையல்?",
    "titleTa": "என்ன சமையல்?",
    "author": "Suresh Balachandar",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/725166/size3/9535ca6dbe1a0b67362b66129050c97f.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/34900-enna-samaiyal?mode=read",
    "descriptionEn": "மீராவின் அப்பா உலர்ந்த திராட்சை வாங்கி வர கடைக்குச் சென்று திரும்பும் முன், அவர் சமைத்திருந்த பாயசம் காணாமல் போய்விட்டது. அவர் வெளியே சென்றிருந்த நேரத்தில் அதைக் குடித்து முடித்தது யார்?",
    "descriptionTa": "மீராவின் அப்பா உலர்ந்த திராட்சை வாங்கி வர கடைக்குச் சென்று திரும்பும் முன், அவர் சமைத்திருந்த பாயசம் காணாமல் போய்விட்டது. அவர் வெளியே சென்றிருந்த நேரத்தில் அதைக் குடித்து முடித்தது யார்?",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_5357",
    "storyId": "5357-poori-ubbuvadu-en",
    "titleEn": "பூரி உப்புவது ஏன்?",
    "titleTa": "பூரி உப்புவது ஏன்?",
    "author": "Rajam Anand",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/712715/size3/ff6bc354d6dd3c347b5b06c130c85cd2.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/5357-poori-ubbuvadu-en?mode=read",
    "descriptionEn": "வட்டமான குண்டு பூரிகள், இந்திய உணவில் முக்கிய அங்கம் வகிப்பவை. அவை எதனால் உப்புகின்றன? இந்த சாதாரண கேள்வியின் பின் பெரிய அறிவியல் விளக்கம் காத்திருக்கிறது.",
    "descriptionTa": "வட்டமான குண்டு பூரிகள், இந்திய உணவில் முக்கிய அங்கம் வகிப்பவை. அவை எதனால் உப்புகின்றன? இந்த சாதாரண கேள்வியின் பின் பெரிய அறிவியல் விளக்கம் காத்திருக்கிறது.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_43335",
    "storyId": "43335-vidhai-semippavarkal",
    "titleEn": "விதை சேமிப்பவர்கள்",
    "titleTa": "விதை சேமிப்பவர்கள்",
    "author": "Rajam Anand",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/89005/size3/c376949d6d1c81338903a0c7d238c634.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/43335-vidhai-semippavarkal?mode=read",
    "descriptionEn": "விதைகளின்றி உண்ண உணவோ, உடுக்க உடையோ சாத்தியமில்லை. உண்மைச் சம்பவத்தைத் தழுவி எழுதப்பட்ட இந்தக் கதை, ஒரு விதை வங்கியை அமைக்க ஒன்றுகூடிய கிராமத்தைப் பற்றியது.",
    "descriptionTa": "விதைகளின்றி உண்ண உணவோ, உடுக்க உடையோ சாத்தியமில்லை. உண்மைச் சம்பவத்தைத் தழுவி எழுதப்பட்ட இந்தக் கதை, ஒரு விதை வங்கியை அமைக்க ஒன்றுகூடிய கிராமத்தைப் பற்றியது.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_17380",
    "storyId": "17380-singam-saapitta-pakoda",
    "titleEn": "சிங்கம் சாப்பிட்ட பக்கோடா",
    "titleTa": "சிங்கம் சாப்பிட்ட பக்கோடா",
    "author": "Sudha  Thilak",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/42881/size3/91de93728ea0174899f988fca4f160ee.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/17380-singam-saapitta-pakoda?mode=read",
    "descriptionEn": "மழை நாட்கள் இவ்வுலகில் சாத்தியங்களுக்கு குறைவில்லை என்பதை உங்களுக்கு உணர வைக்கிறதா? இக்கதையில் வரும் சிங்கம் நிச்சயமாக அப்படித் தான் நம்புகிறது. ஒரு மழை நாளில் மிருகக்காட்சி சாலையிலிருந்து விடுமுறை எடுத்துக் கொண்ட சிங்கத்தை சந்திக்க இக்கதையைப் படியுங்கள்! இக்கதையில் வரும் குழந்தைகளைப் போல் நீங்களும் மகிழுங்கள்! கதாசிரியர் இது ‘கிட்டத்தட்ட நிஜக்கதையே’ என மெய்ப்பிக்கிறார்.\r\n",
    "descriptionTa": "மழை நாட்கள் இவ்வுலகில் சாத்தியங்களுக்கு குறைவில்லை என்பதை உங்களுக்கு உணர வைக்கிறதா? இக்கதையில் வரும் சிங்கம் நிச்சயமாக அப்படித் தான் நம்புகிறது. ஒரு மழை நாளில் மிருகக்காட்சி சாலையிலிருந்து விடுமுறை எடுத்துக் கொண்ட சிங்கத்தை சந்திக்க இக்கதையைப் படியுங்கள்! இக்கதையில் வரும் குழந்தைகளைப் போல் நீங்களும் மகிழுங்கள்! கதாசிரியர் இது ‘கிட்டத்தட்ட நிஜக்கதையே’ என மெய்ப்பிக்கிறார்.\r\n",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_10909",
    "storyId": "10909-uyil",
    "titleEn": "உயில்",
    "titleTa": "உயில்",
    "author": "S. Jayaraman",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/723049/size3/5709a651ff168831b050f19140068505.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/10909-uyil?mode=read",
    "descriptionEn": "எப்படி பதினேழு ஒட்டகங்களில் பாதியை ஒருவருக்குக் கொடுப்பது? இந்த கதை, அக்குழப்பத்தைத் தீர்த்து தன் மகன்களிடையே பிளவு ஏற்படாமல் தடுத்த ருகையா காதூன் என்ற ஒரு தாயின் புத்தி கூர்மையையும், அப்துல்லா-பின்-சாத் என்ற ஒரு தந்தையின் விவேகத்தையும் விளக்குகிறது.",
    "descriptionTa": "எப்படி பதினேழு ஒட்டகங்களில் பாதியை ஒருவருக்குக் கொடுப்பது? இந்த கதை, அக்குழப்பத்தைத் தீர்த்து தன் மகன்களிடையே பிளவு ஏற்படாமல் தடுத்த ருகையா காதூன் என்ற ஒரு தாயின் புத்தி கூர்மையையும், அப்துல்லா-பின்-சாத் என்ற ஒரு தந்தையின் விவேகத்தையும் விளக்குகிறது.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_5171",
    "storyId": "5171-jadavin-kaadu",
    "titleEn": "ஜாதவின் காடு",
    "titleTa": "ஜாதவின் காடு",
    "author": "N. Chokkan",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/712342/size3/d8de7d5aebdf7754bbf81fd93c25dba0.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/5171-jadavin-kaadu?mode=read",
    "descriptionEn": "இந்த உலகத்திலேயே மிகச்சிறந்த ஒரு வேலையை செய்துகொண்டிருக்கிறார் ஜாதவ்: காடுகளை உருவாக்குதல்!\r\nஅவர் காடுகளை எப்படி உருவாக்குகிறார்? தெரிந்துகொள்ள இந்தப் புத்தகத்தை வாசியுங்கள்.",
    "descriptionTa": "இந்த உலகத்திலேயே மிகச்சிறந்த ஒரு வேலையை செய்துகொண்டிருக்கிறார் ஜாதவ்: காடுகளை உருவாக்குதல்!\r\nஅவர் காடுகளை எப்படி உருவாக்குகிறார்? தெரிந்துகொள்ள இந்தப் புத்தகத்தை வாசியுங்கள்.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_39644",
    "storyId": "39644-kaanamalpona-nilaa",
    "titleEn": "காணாமல் போன நிலா",
    "titleTa": "காணாமல் போன நிலா",
    "author": "Rajam Anand",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/85034/size3/3d21e461e24f11386172abfe1e74d4b4.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/39644-kaanamalpona-nilaa?mode=read",
    "descriptionEn": "ஒரு நாள் இரவு,  நிலா கடலிலிருந்து எழும்பவில்லை. மைஷாவும் அவளது நண்பனான பறக்கும் மீன் உச்லியும், நிலாவைத் தேடத் தொடங்குகின்றனர்.. ஆனால், வெளிச்சமே இல்லாமல் எப்படி நிலாவைத் தேட முடியும்?",
    "descriptionTa": "ஒரு நாள் இரவு,  நிலா கடலிலிருந்து எழும்பவில்லை. மைஷாவும் அவளது நண்பனான பறக்கும் மீன் உச்லியும், நிலாவைத் தேடத் தொடங்குகின்றனர்.. ஆனால், வெளிச்சமே இல்லாமல் எப்படி நிலாவைத் தேட முடியும்?",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_24877",
    "storyId": "24877-puchkuvukku-oru-puthagam",
    "titleEn": "புச்குவுக்கு ஒரு புத்தகம்",
    "titleTa": "புச்குவுக்கு ஒரு புத்தகம்",
    "author": "S Krishnan",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/117108/size3/e8e1a6d2e2ced15a142777ab5ebacbf5.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/24877-puchkuvukku-oru-puthagam?mode=read",
    "descriptionEn": "புச்கு எல்லாப் புத்தகங்களையும் படித்து முடித்துவிட்டாள். பின்னர்,  நூலக அலமாரியின் மேல் அடுக்கில்  இன்னும் பல புத்தகங்கள்  இருப்பதைக் கண்டுபிடித்தாள். ஆனால் புச்குவின் உயரம் குறைவு. அலமாரியோ மிக உயரமானது. அவளுக்குப் பிடித்த புத்தகங்களை அவள் எப்படி அடையப் போகிறாள்?",
    "descriptionTa": "புச்கு எல்லாப் புத்தகங்களையும் படித்து முடித்துவிட்டாள். பின்னர்,  நூலக அலமாரியின் மேல் அடுக்கில்  இன்னும் பல புத்தகங்கள்  இருப்பதைக் கண்டுபிடித்தாள். ஆனால் புச்குவின் உயரம் குறைவு. அலமாரியோ மிக உயரமானது. அவளுக்குப் பிடித்த புத்தகங்களை அவள் எப்படி அடையப் போகிறாள்?",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_39446",
    "storyId": "39446-visiladikkum-vinjaana-vedikkai",
    "titleEn": "விசிலடிக்கும் விஞ்ஞான வேடிக்கை",
    "titleTa": "விசிலடிக்கும் விஞ்ஞான வேடிக்கை",
    "author": "Irulneeki Ganesan",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/713820/size3/735e2105b6ba7d1d28b34e8940ff584c.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/39446-visiladikkum-vinjaana-vedikkai?mode=read",
    "descriptionEn": "பிரஷர் குக்கர் மூன்று விசில் அடித்தவுடன் அடுப்பை அணைக்குமாறு அம்மா நிவியிடம் சொல்கிறார். ஆனால் நிவிக்கோ தன்னுடைய புதிய புத்தகத்தைப் படிப்பதில்தான் ஆர்வம். அவள் புத்திசாலித்தனமாக எப்படி இரண்டையுமே செய்கிறாள் என்று பார்ப்போமே.",
    "descriptionTa": "பிரஷர் குக்கர் மூன்று விசில் அடித்தவுடன் அடுப்பை அணைக்குமாறு அம்மா நிவியிடம் சொல்கிறார். ஆனால் நிவிக்கோ தன்னுடைய புதிய புத்தகத்தைப் படிப்பதில்தான் ஆர்வம். அவள் புத்திசாலித்தனமாக எப்படி இரண்டையுமே செய்கிறாள் என்று பார்ப்போமே.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_28567",
    "storyId": "28567-somberi-mama",
    "titleEn": "சோம்பேறி மாமா",
    "titleTa": "சோம்பேறி மாமா",
    "author": "Violet வயலட்",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/714195/size3/3774467adccf3e2d6841cf43aa22d880.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/28567-somberi-mama?mode=read",
    "descriptionEn": "சோம்பேறியான ரகு மாமா தனது நாற்காலியிலிருந்து நகராமலேயே சாகசப் பயணங்களை மேற்கொள்வதாகச் சொல்லும்போது, அமிஷும் சோனியும் ஆச்சரியம் அடைகிறார்கள்.  அதை எப்படிச் செய்கிறார்? அமிஷும் சோனியும் கூட அந்த சாகசப் பயணங்களில் உடன் செல்லமுடியுமா?",
    "descriptionTa": "சோம்பேறியான ரகு மாமா தனது நாற்காலியிலிருந்து நகராமலேயே சாகசப் பயணங்களை மேற்கொள்வதாகச் சொல்லும்போது, அமிஷும் சோனியும் ஆச்சரியம் அடைகிறார்கள்.  அதை எப்படிச் செய்கிறார்? அமிஷும் சோனியும் கூட அந்த சாகசப் பயணங்களில் உடன் செல்லமுடியுமா?",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_114553",
    "storyId": "114553-naan-valarndhadhum",
    "titleEn": "நான் வளர்ந்ததும்",
    "titleTa": "நான் வளர்ந்ததும்",
    "author": "Livingson Remi",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/524494/size3/593a3b57ef62de289db490553a419cf1.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/114553-naan-valarndhadhum?mode=read",
    "descriptionEn": "என் பெயர் பாப்போரி. நான் வளர்ந்து பொறியாளர் ஆகப் போகிறேன்.\r\nஇந்தப் புத்தகம் நான் உருவாக்கப் போகும் அனைத்தையும் பற்றியது. \r\nஇதில் கடினமான சொற்கள் பல உள்ளன. அதேசமயம் வீரதீர சாகசங்களுக்கும் குறைவில்லை. வாருங்கள், என்னுடன் சேர்ந்துகொள்ளுங்கள்!",
    "descriptionTa": "என் பெயர் பாப்போரி. நான் வளர்ந்து பொறியாளர் ஆகப் போகிறேன்.\r\nஇந்தப் புத்தகம் நான் உருவாக்கப் போகும் அனைத்தையும் பற்றியது. \r\nஇதில் கடினமான சொற்கள் பல உள்ளன. அதேசமயம் வீரதீர சாகசங்களுக்கும் குறைவில்லை. வாருங்கள், என்னுடன் சேர்ந்துகொள்ளுங்கள்!",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38888",
    "storyId": "38888-natpu-paalam",
    "titleEn": "நட்புப் பாலம்",
    "titleTa": "நட்புப் பாலம்",
    "author": "Rajam Anand",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/724111/size3/9c28a54e71a2ce6ddcd0ec16827ffc81.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38888-natpu-paalam?mode=read",
    "descriptionEn": "மேரியும்,  ஜோசனாவும் அடுத்தடுத்த வீட்டில் வசிக்கும் உயிர்த்தோழிகள். அவர்களுக்கிடையே சண்டை வந்தபோது, எப்படி தன் தோழியை சமாதானப்படுத்துவது என்று மேரி யோசிக்கிறாள்.",
    "descriptionTa": "மேரியும்,  ஜோசனாவும் அடுத்தடுத்த வீட்டில் வசிக்கும் உயிர்த்தோழிகள். அவர்களுக்கிடையே சண்டை வந்தபோது, எப்படி தன் தோழியை சமாதானப்படுத்துவது என்று மேரி யோசிக்கிறாள்.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_13799",
    "storyId": "13799-migach-chirantha-veedu",
    "titleEn": "மிகச் சிறந்த வீடு…",
    "titleTa": "மிகச் சிறந்த வீடு…",
    "author": "N. Chokkan",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/724108/size3/44fe170ad046b14664899d1727befc14.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/13799-migach-chirantha-veedu?mode=read",
    "descriptionEn": "பெரியது, சிறியது, வட்டமானது, சதுரமானது, கனமானது, லேசானது ...இல்லங்களில் பல வகைகள் உண்டு. அவற்றினிடையே என்னென்ன வேறுபாடு என்பதை அறிந்துகொண்டு உங்கள் வீட்டை நீங்களே உருவாக்குங்கள். அது எப்படி என்பதை எங்கள் குட்டிக் கட்டடக் கலைஞர் சொல்லித்தருகிறார், தெரிந்துகொள்ளுங்கள் !\r\n",
    "descriptionTa": "பெரியது, சிறியது, வட்டமானது, சதுரமானது, கனமானது, லேசானது ...இல்லங்களில் பல வகைகள் உண்டு. அவற்றினிடையே என்னென்ன வேறுபாடு என்பதை அறிந்துகொண்டு உங்கள் வீட்டை நீங்களே உருவாக்குங்கள். அது எப்படி என்பதை எங்கள் குட்டிக் கட்டடக் கலைஞர் சொல்லித்தருகிறார், தெரிந்துகொள்ளுங்கள் !\r\n",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_126615",
    "storyId": "126615-laddu-kuriyeedu",
    "titleEn": "லட்டு குறியீடு",
    "titleTa": "லட்டு குறியீடு",
    "author": "M. Gunavathy",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/180166/size3/49c85a9527750e46622accc20a0c24f0.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/126615-laddu-kuriyeedu?mode=read",
    "descriptionEn": "ராகுலும் ரித்விக்கும் வகுப்புக்குக் கொண்டுவரும் தின்பண்டங்கள் எப்போதும் நண்பர்களிடம் மாட்டி காலியாகி விடுகின்றன. அதனால், ராகுலும் ரித்விக்கும் தங்கள் தின்பண்டங்களைப் பாதுகாக்க ரகசியக் குறியீடு ஒன்றை உருவாக்கினர்.",
    "descriptionTa": "ராகுலும் ரித்விக்கும் வகுப்புக்குக் கொண்டுவரும் தின்பண்டங்கள் எப்போதும் நண்பர்களிடம் மாட்டி காலியாகி விடுகின்றன. அதனால், ராகுலும் ரித்விக்கும் தங்கள் தின்பண்டங்களைப் பாதுகாக்க ரகசியக் குறியீடு ஒன்றை உருவாக்கினர்.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_67624",
    "storyId": "67624-sirippai-adakkave-mudiyaatha-sirumi",
    "titleEn": "சிரிப்பை அடக்கவே முடியாத சிறுமி",
    "titleTa": "சிரிப்பை அடக்கவே முடியாத சிறுமி",
    "author": "Priya  Muthukumar",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/718145/size3/8f27fe5f72c50232be4f992cd4a2eaea.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/67624-sirippai-adakkave-mudiyaatha-sirumi?mode=read",
    "descriptionEn": "டி. சுந்தரி தினமும் ஏதாவ‍து பிரச்சினையில் மாட்டிக்கொள்வாள். ஏனென்றால், பல விஷயங்கள் அவளுக்கு சிரிப்பு மூட்டின. அவளால் வாயை மூடிக்கொண்டு இருக்கவே முடியாது. தன்னிடம் ஏதாவது குறை இருக்கிறதா, இல்லை எப்போதும் சிரித்துக் கொண்டே இருக்கலாமா? தெரிந்துகொள்ள ஆசைப்படுகிறாள் டி. சுந்தரி.",
    "descriptionTa": "டி. சுந்தரி தினமும் ஏதாவ‍து பிரச்சினையில் மாட்டிக்கொள்வாள். ஏனென்றால், பல விஷயங்கள் அவளுக்கு சிரிப்பு மூட்டின. அவளால் வாயை மூடிக்கொண்டு இருக்கவே முடியாது. தன்னிடம் ஏதாவது குறை இருக்கிறதா, இல்லை எப்போதும் சிரித்துக் கொண்டே இருக்கலாமா? தெரிந்துகொள்ள ஆசைப்படுகிறாள் டி. சுந்தரி.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_28745",
    "storyId": "28745-silandhiyai-thedi",
    "titleEn": "சிலந்தியைத் தேடி",
    "titleTa": "சிலந்தியைத் தேடி",
    "author": "Malarkody",
    "level": "3",
    "levelLabelEn": "Level 3 (Developing)",
    "levelLabelTa": "நிலை 3 (மூன்றாம் நிலை)",
    "targetGrades": "Year 4, Year 5",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/724142/size3/2def5022f432c5f5ad671e002ebe95c8.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/28745-silandhiyai-thedi?mode=read",
    "descriptionEn": "காவேரியும் ஷிவியும் அவர்களுடைய தோழி ஷாமாவுடன் சேர்ந்து சிலந்திகளைத் தேடிச் செல்கின்றனர்.",
    "descriptionTa": "காவேரியும் ஷிவியும் அவர்களுடைய தோழி ஷாமாவுடன் சேர்ந்து சிலந்திகளைத் தேடிச் செல்கின்றனர்.",
    "readingPoints": 70,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_14796",
    "storyId": "14796-kokku-karpitha-paadam",
    "titleEn": "கொக்கு கற்பித்த பாடம்",
    "titleTa": "கொக்கு கற்பித்த பாடம்",
    "author": "Sudha  Thilak",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/722857/size3/6fb60231ce2aa30ab7722953f3d0c925.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/14796-kokku-karpitha-paadam?mode=read",
    "descriptionEn": "கிராமங்களில் வளரும் குழந்தைகள், பிற உயிரினங்களின் அருகாமையில் நெருங்கி வளர்கிறார்கள். வாழ்க்கையின் சில முக்கியப் பாடங்களை, குழந்தைகள் எப்படிக் கற்றுக் கொள்கிறார்கள் என்பதை மனதைத் தொடும் \r\nஇந்தக் கதையில் படியுங்கள்!",
    "descriptionTa": "கிராமங்களில் வளரும் குழந்தைகள், பிற உயிரினங்களின் அருகாமையில் நெருங்கி வளர்கிறார்கள். வாழ்க்கையின் சில முக்கியப் பாடங்களை, குழந்தைகள் எப்படிக் கற்றுக் கொள்கிறார்கள் என்பதை மனதைத் தொடும் \r\nஇந்தக் கதையில் படியுங்கள்!",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_15070",
    "storyId": "15070-kadalaamaiyin-kadhai",
    "titleEn": "கடல் ஆமையின் கதை",
    "titleTa": "கடல் ஆமையின் கதை",
    "author": "S. Jayaraman",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/27753/size3/e21f0014824d4500d005ff02b9529442.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/15070-kadalaamaiyin-kadhai?mode=read",
    "descriptionEn": "ஆள் அரவமற்ற கடற்கரைகளில், இருளின் போர்வையில், பகலெல்லாம் சூரியனின் ஒளியால் சூடுபடுத்தப்பட்ட ரிட்லி கடல் ஆமைகளின் முட்டைகள் பொரிந்து குஞ்சுகளாகின்றன. அவைகளில் ஒன்றுதான் நமக்குக் கதை சொல்லும் கடல் ஆமைக்குஞ்சு. கடற்கரையில் வழி தவறிவிடாமலும், உண்ணக் காத்திருக்கும் எதிரிகளின் கண்ணில் படாமலும் கடலுக்குள் சென்றதில் குஞ்சுக்குப் பெருமகிழ்ச்சி. ஆனால், நமது ஆலிவ் ரிட்லி கடல் ஆமைக்குஞ்சு, ஆபத்தான கடல் பயணத்தைப் பத்திரமாய் கடக்குமா? கொடூரமான சுறாக்களையும், பயங்கரமான மீன்பிடி வலைகளையும் தாண்டி தப்பித்து வந்து, அதனுடைய விடலைப்பருவம் வரை வாழ்ந்து, தனது என்று சொல்லிக்கொள்ள கொத்தாக முட்டைகளை கடற்கரையில் இடும் சந்தோஷம் அவளுக்கும் கிடைக்குமா?  \r\n\r\nதெரிந்து கொள்ளப் படியுங்கள், ஆலிவ் ரிட்லி கடல் ஆமைக்குஞ்சு ஒன்றின் வாழ்க்கைப் பயணக்கதையை! ",
    "descriptionTa": "ஆள் அரவமற்ற கடற்கரைகளில், இருளின் போர்வையில், பகலெல்லாம் சூரியனின் ஒளியால் சூடுபடுத்தப்பட்ட ரிட்லி கடல் ஆமைகளின் முட்டைகள் பொரிந்து குஞ்சுகளாகின்றன. அவைகளில் ஒன்றுதான் நமக்குக் கதை சொல்லும் கடல் ஆமைக்குஞ்சு. கடற்கரையில் வழி தவறிவிடாமலும், உண்ணக் காத்திருக்கும் எதிரிகளின் கண்ணில் படாமலும் கடலுக்குள் சென்றதில் குஞ்சுக்குப் பெருமகிழ்ச்சி. ஆனால், நமது ஆலிவ் ரிட்லி கடல் ஆமைக்குஞ்சு, ஆபத்தான கடல் பயணத்தைப் பத்திரமாய் கடக்குமா? கொடூரமான சுறாக்களையும், பயங்கரமான மீன்பிடி வலைகளையும் தாண்டி தப்பித்து வந்து, அதனுடைய விடலைப்பருவம் வரை வாழ்ந்து, தனது என்று சொல்லிக்கொள்ள கொத்தாக முட்டைகளை கடற்கரையில் இடும் சந்தோஷம் அவளுக்கும் கிடைக்குமா?  \r\n\r\nதெரிந்து கொள்ளப் படியுங்கள், ஆலிவ் ரிட்லி கடல் ஆமைக்குஞ்சு ஒன்றின் வாழ்க்கைப் பயணக்கதையை! ",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_13252",
    "storyId": "13252-captain-arya",
    "titleEn": "கேப்டன் ஆர்யா",
    "titleTa": "கேப்டன் ஆர்யா",
    "author": "Violet வயலட்",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/713815/size3/86bf40b3b913d9d94bc04157998a8257.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/13252-captain-arya?mode=read",
    "descriptionEn": "ஆர்யா எப்போதும் பறப்பதைப் பற்றியே கனவு கண்டுகொண்டு இருந்தாள். ஆர்யா தன்னுடைய கனவுகளைப் பின்பற்றியதைப்  பற்றிப் படித்து, அவள் முதல்முறையாக விமானம் ஓட்டும்போது அவளோடு நீங்களும் விமான ஓட்டுநர் அறையில் சேர்ந்துகொள்ளுங்கள். இது உண்மையிலேயே ரொம்ப விசேஷமான நாள்தான்!",
    "descriptionTa": "ஆர்யா எப்போதும் பறப்பதைப் பற்றியே கனவு கண்டுகொண்டு இருந்தாள். ஆர்யா தன்னுடைய கனவுகளைப் பின்பற்றியதைப்  பற்றிப் படித்து, அவள் முதல்முறையாக விமானம் ஓட்டும்போது அவளோடு நீங்களும் விமான ஓட்டுநர் அறையில் சேர்ந்துகொள்ளுங்கள். இது உண்மையிலேயே ரொம்ப விசேஷமான நாள்தான்!",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_39625",
    "storyId": "39625-thanneraith-thaedi",
    "titleEn": "தண்ணீரைத் தேடி",
    "titleTa": "தண்ணீரைத் தேடி",
    "author": "S Krishnan",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/724112/size3/1c190e70406411ab7431038cc2aaea88.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/39625-thanneraith-thaedi?mode=read",
    "descriptionEn": "ரஞ்சுவின் கிராமத்தில் உள்ள நீர்நிலை வறண்டுவிடுகிறது, தண்ணீரைக் கண்டுபிடிக்க அவள் புறப்படுகிறாள். துப்பறிவாளர் ரஞ்சுவுடன் நீங்களும் செல்லுங்கள்.",
    "descriptionTa": "ரஞ்சுவின் கிராமத்தில் உள்ள நீர்நிலை வறண்டுவிடுகிறது, தண்ணீரைக் கண்டுபிடிக்க அவள் புறப்படுகிறாள். துப்பறிவாளர் ரஞ்சுவுடன் நீங்களும் செல்லுங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_12472",
    "storyId": "12472-kaakasaaras",
    "titleEn": "காகசாரஸ்",
    "titleTa": "காகசாரஸ்",
    "author": "Praba Ram, Sheela Preuitt",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/713582/size3/b6cae5197a37599ee424fd455742c661.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/12472-kaakasaaras?mode=read",
    "descriptionEn": "ராஜிக்கு இந்த நாள் மிகவும் கடினமாகத் தொடங்குகிறது. முதலில், ஒரு காகம் அவளது பஜ்ஜியை விழுங்கி விடுகிறது. பிறகு, அது அவளது சிறந்த நண்பனான சலீமை  சாப்பிட முயற்சி செய்கிறது! பின்னர், அதைவிட மோசமாக ஒன்று நடக்கிறது, நிறைவாக, எல்லாம் நன்மையில் முடிகிறது.",
    "descriptionTa": "ராஜிக்கு இந்த நாள் மிகவும் கடினமாகத் தொடங்குகிறது. முதலில், ஒரு காகம் அவளது பஜ்ஜியை விழுங்கி விடுகிறது. பிறகு, அது அவளது சிறந்த நண்பனான சலீமை  சாப்பிட முயற்சி செய்கிறது! பின்னர், அதைவிட மோசமாக ஒன்று நடக்கிறது, நிறைவாக, எல்லாம் நன்மையில் முடிகிறது.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_941",
    "storyId": "941-kalluvin-ulagam-2-medayil-kurangguthanam",
    "titleEn": "கல்லுவின் உலகம் 2 மேடையில் குரங்குத்தனம்!",
    "titleTa": "கல்லுவின் உலகம் 2 மேடையில் குரங்குத்தனம்!",
    "author": "N. Chokkan",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/722423/size3/37044e541d68c258209aa756f201868c.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/941-kalluvin-ulagam-2-medayil-kurangguthanam?mode=read",
    "descriptionEn": "கல்லுவின் உலகத்துக்கு உங்களை வரவேற்கிறோம்!\r\nஇந்தக் கிராமத்தில் நல்லவர்களும் உண்டு. கெட்டவர்களும் உண்டு. கல்லுவும் அவனுடைய தோழர்களும் சுறுசுறுப்பான சுட்டிகள். கிராமத்து வழக்கங்களைக் கேள்வி கேட்பார்கள், வம்பு பண்ணுகிறவர்களுக்குப் பதிலடி கொடுப்பார்கள், பிரச்னைகளுக்குப் புதுமையான தீர்வுகளைக் கண்டுபிடிப்பார்கள்.\r\nஇந்தக் கதையில், கல்லுவும் அவனுடைய கோஷ்டியும் ராம்லீலா கொண்டாட்டங்களில் கலந்துகொள்கிறார்கள். அப்புறம் என்ன ஆச்சு? உள்ளே படியுங்கள்.",
    "descriptionTa": "கல்லுவின் உலகத்துக்கு உங்களை வரவேற்கிறோம்!\r\nஇந்தக் கிராமத்தில் நல்லவர்களும் உண்டு. கெட்டவர்களும் உண்டு. கல்லுவும் அவனுடைய தோழர்களும் சுறுசுறுப்பான சுட்டிகள். கிராமத்து வழக்கங்களைக் கேள்வி கேட்பார்கள், வம்பு பண்ணுகிறவர்களுக்குப் பதிலடி கொடுப்பார்கள், பிரச்னைகளுக்குப் புதுமையான தீர்வுகளைக் கண்டுபிடிப்பார்கள்.\r\nஇந்தக் கதையில், கல்லுவும் அவனுடைய கோஷ்டியும் ராம்லீலா கொண்டாட்டங்களில் கலந்துகொள்கிறார்கள். அப்புறம் என்ன ஆச்சு? உள்ளே படியுங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_636287",
    "storyId": "636287-somberi-anansi",
    "titleEn": "சோம்பேறி அனன்சி",
    "titleTa": "சோம்பேறி அனன்சி",
    "author": "Paula Sharon",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/141916/size3/8c5af656393928f97fa73d07f95af337.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/636287-somberi-anansi?mode=read",
    "descriptionEn": "சிலந்திகளுக்கு நீண்ட மெல்லிய கால்கள் இருப்பதற்கான காரணம் என்னவோ?",
    "descriptionTa": "சிலந்திகளுக்கு நீண்ட மெல்லிய கால்கள் இருப்பதற்கான காரணம் என்னவோ?",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_150624",
    "storyId": "150624-arunum-marmamaaligaiyum",
    "titleEn": "அருணும் மர்மமாளிகையும்",
    "titleTa": "அருணும் மர்மமாளிகையும்",
    "author": "Ramki J",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/202930/size3/56578534ef3390627c24976344c17172.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/150624-arunum-marmamaaligaiyum?mode=read",
    "descriptionEn": "அருணும் அருணாச்சலமும் ஒரு பாழடைந்த மர்ம மாளிகைக்குள் சிக்கிக் கொண்டார்கள்! அவர்கள் வெளியேற ஒரே வழி, ஒரு மின்னணுச் சுற்றை அமைப்பதுதான். ஆனால், அவர்கள் அதை எப்படிச் செய்வார்கள்?",
    "descriptionTa": "அருணும் அருணாச்சலமும் ஒரு பாழடைந்த மர்ம மாளிகைக்குள் சிக்கிக் கொண்டார்கள்! அவர்கள் வெளியேற ஒரே வழி, ஒரு மின்னணுச் சுற்றை அமைப்பதுதான். ஆனால், அவர்கள் அதை எப்படிச் செய்வார்கள்?",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_95163",
    "storyId": "95163-panaththin-payanam",
    "titleEn": "பணத்தின் பயணம்",
    "titleTa": "பணத்தின் பயணம்",
    "author": "Sandhya Jaichandren",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/723603/size3/ac32ac4ee2b4016aa6e508125a0192d4.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/95163-panaththin-payanam?mode=read",
    "descriptionEn": "‘ரூபாய், நாணய’த் தொடர் பணம் குறித்த பயனுள்ள பல விவரங்களைக் குழந்தைகளுக்குத் தருகிறது. அதன்மூலம், மாறிக்கொண்டேவரும் இந்த உலகில் அவர்கள் வளர்ந்து பெரியவர்களாகும் போது பணத்தை விவேகத்தோடு புத்திசாலித்தனமாகப் பயன்படுத்த அவர்களுக்கு உதவிசெய்கிறது. நாணயங்கள் எவற்றைக்கொண்டு தயாரிக்கப்பட்டன? மனிதர்கள் எவ்வாறு பணத்தைச் சம்பாதிக்கிறார்கள், சேமிக்கிறார்கள், பயன்படுத்துகிறார்கள்? போதுமான அளவு பணம் கையில் இல்லாத நிலையிலும், ஒரு குடும்பம் தான் விரும்பிய குளிர்சாதனப் பெட்டியை உடனே வாங்கிவிட இயலுமா? இவற்றையும் இன்னும் பலவற்றையும் அறிந்துகொள்ள, ‘ரூபாய், நாணய’த் தொடரின் இரண்டாவது புத்தகமான ‘பணத்தின் பயணம்’ உங்களுக்கு உதவும்.",
    "descriptionTa": "‘ரூபாய், நாணய’த் தொடர் பணம் குறித்த பயனுள்ள பல விவரங்களைக் குழந்தைகளுக்குத் தருகிறது. அதன்மூலம், மாறிக்கொண்டேவரும் இந்த உலகில் அவர்கள் வளர்ந்து பெரியவர்களாகும் போது பணத்தை விவேகத்தோடு புத்திசாலித்தனமாகப் பயன்படுத்த அவர்களுக்கு உதவிசெய்கிறது. நாணயங்கள் எவற்றைக்கொண்டு தயாரிக்கப்பட்டன? மனிதர்கள் எவ்வாறு பணத்தைச் சம்பாதிக்கிறார்கள், சேமிக்கிறார்கள், பயன்படுத்துகிறார்கள்? போதுமான அளவு பணம் கையில் இல்லாத நிலையிலும், ஒரு குடும்பம் தான் விரும்பிய குளிர்சாதனப் பெட்டியை உடனே வாங்கிவிட இயலுமா? இவற்றையும் இன்னும் பலவற்றையும் அறிந்துகொள்ள, ‘ரூபாய், நாணய’த் தொடரின் இரண்டாவது புத்தகமான ‘பணத்தின் பயணம்’ உங்களுக்கு உதவும்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_113938",
    "storyId": "113938-thanneerin-osai",
    "titleEn": "தண்ணீரின் ஓசை",
    "titleTa": "தண்ணீரின் ஓசை",
    "author": "Ramya Satheesh",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/721325/size3/07c19bca39403c868921d7fe61cc44d2.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/113938-thanneerin-osai?mode=read",
    "descriptionEn": "வர்ஷாவும் அவள் அப்பாவும் காட்டின் அருகே வசித்தனர்.  கடுமையான ஒரு கோடையில் வர்ஷா வெப்பத்தால் வாடிக்கொண்டிருந்தாள்.  ஒருநாள் வர்ஷாவுக்கு வித்தியாசமான சத்தம் ஒன்று கேட்டது. அது என்னவென்று துப்பறியக் கிளம்பினாள். அவளுக்கு மட்டுமே கேட்கும் அந்தச் சத்தம் என்னவாக இருக்கும் என்று யோசித்தாள். வர்ஷா, என்ன கண்டுபிடிக்கப் போகிறாள்? அப்பா அவளை நம்புவாரா? ",
    "descriptionTa": "வர்ஷாவும் அவள் அப்பாவும் காட்டின் அருகே வசித்தனர்.  கடுமையான ஒரு கோடையில் வர்ஷா வெப்பத்தால் வாடிக்கொண்டிருந்தாள்.  ஒருநாள் வர்ஷாவுக்கு வித்தியாசமான சத்தம் ஒன்று கேட்டது. அது என்னவென்று துப்பறியக் கிளம்பினாள். அவளுக்கு மட்டுமே கேட்கும் அந்தச் சத்தம் என்னவாக இருக்கும் என்று யோசித்தாள். வர்ஷா, என்ன கண்டுபிடிக்கப் போகிறாள்? அப்பா அவளை நம்புவாரா? ",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_12937",
    "storyId": "12937-kadalai-thediya-thavalai",
    "titleEn": "கடலைத் தேடிய தவளை",
    "titleTa": "கடலைத் தேடிய தவளை",
    "author": "K. R. Lenin",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/29639/size3/cfbcf6f1aa30ca587bf2ba269bb87a31.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/12937-kadalai-thediya-thavalai?mode=read",
    "descriptionEn": "மரத்தில் வாழும் தவளையான தாமு விரிந்து, பரந்த நீலக் கடலைப் பார்க்க விரும்புகிறான். நீங்களும் அவனோடு மேற்கு மலைத் தொடருக்கு ஒரு நடைப் பயணம் போகலாமே! அங்கே ஏராளமான வேடிக்கையான, குண்டான, மனத்தை வசீகரிக்கும் பலவிதமான உயிரினங்கள் உண்டு. இயற்கையின் சிறப்பம்சங்களை நகைச்சுவையுடன் சுவாரசியமான கதைமூலம் சொல்கிறது இந்தப் புத்தகம்.",
    "descriptionTa": "மரத்தில் வாழும் தவளையான தாமு விரிந்து, பரந்த நீலக் கடலைப் பார்க்க விரும்புகிறான். நீங்களும் அவனோடு மேற்கு மலைத் தொடருக்கு ஒரு நடைப் பயணம் போகலாமே! அங்கே ஏராளமான வேடிக்கையான, குண்டான, மனத்தை வசீகரிக்கும் பலவிதமான உயிரினங்கள் உண்டு. இயற்கையின் சிறப்பம்சங்களை நகைச்சுவையுடன் சுவாரசியமான கதைமூலம் சொல்கிறது இந்தப் புத்தகம்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_125062",
    "storyId": "125062-inaiyatthil-tholaindha-kunaal",
    "titleEn": "இணையத்தில் தொலைந்த குணால்",
    "titleTa": "இணையத்தில் தொலைந்த குணால்",
    "author": "Subhashini Annamalai",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/181775/size3/f1f3e98219874cda59f16f00331eea98.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/125062-inaiyatthil-tholaindha-kunaal?mode=read",
    "descriptionEn": "குணால் இணையத்தில் தொலைந்து விடுகிறான். இணையத்தின் வழியாக ஒரு அறிவியல் புனைவுப் பயணம் செய்து, அவன் எப்படி வீட்டுக்கு வழி கண்டுபிடிக்கிறான் என்று பார்ப்போம், வாருங்கள்.",
    "descriptionTa": "குணால் இணையத்தில் தொலைந்து விடுகிறான். இணையத்தின் வழியாக ஒரு அறிவியல் புனைவுப் பயணம் செய்து, அவன் எப்படி வீட்டுக்கு வழி கண்டுபிடிக்கிறான் என்று பார்ப்போம், வாருங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_5269",
    "storyId": "5269-udavum-karam",
    "titleEn": "உதவும் கரம்",
    "titleTa": "உதவும் கரம்",
    "author": "N. Chokkan",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/710834/size3/51608bab8fd9f6d6579d86ce735c1dcb.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/5269-udavum-karam?mode=read",
    "descriptionEn": "வகுப்புக்கு ஒரு புதிய பெண் வந்திருக்கிறாளாம். அவள் பள்ளியைச் சுற்றிப்பார்த்துத் தெரிந்துகொள்ள நான் உதவவேண்டுமாம். ஆனால்... அவள் நம்மைப்போல் இல்லையே! அவளுக்கு நான் எப்படி உதவுவது?\r\nஅனைவருக்கும் இவ்வுலகில் இடம்வேண்டும். எல்லோரும் நட்போடு வாழவேண்டும் என்பதை உணர்த்தும் ஓர் அற்புதமான கதை!",
    "descriptionTa": "வகுப்புக்கு ஒரு புதிய பெண் வந்திருக்கிறாளாம். அவள் பள்ளியைச் சுற்றிப்பார்த்துத் தெரிந்துகொள்ள நான் உதவவேண்டுமாம். ஆனால்... அவள் நம்மைப்போல் இல்லையே! அவளுக்கு நான் எப்படி உதவுவது?\r\nஅனைவருக்கும் இவ்வுலகில் இடம்வேண்டும். எல்லோரும் நட்போடு வாழவேண்டும் என்பதை உணர்த்தும் ஓர் அற்புதமான கதை!",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_13254",
    "storyId": "13254-raajuvin-muthal-vimaanap-payanam",
    "titleEn": "ராஜுவின் முதல் விமானப்பயணம்",
    "titleTa": "ராஜுவின் முதல் விமானப்பயணம்",
    "author": "Violet வயலட்",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/713806/size3/2625fe2f51bccee02b4391276a85eca7.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/13254-raajuvin-muthal-vimaanap-payanam?mode=read",
    "descriptionEn": "ராஜுவின் கனவுகள் எல்லாம் பறப்பதைப் பற்றிதான். அவன் முதல்முறையாக விமானத்தில் பறக்கத் தயாராகும்போது, அவனுடைய உற்சாகத்தில் நீங்களும் சேர்ந்துகொள்ளுங்கள். இது உண்மையிலேயே மிகச் சிறப்பான நாள்தான்!",
    "descriptionTa": "ராஜுவின் கனவுகள் எல்லாம் பறப்பதைப் பற்றிதான். அவன் முதல்முறையாக விமானத்தில் பறக்கத் தயாராகும்போது, அவனுடைய உற்சாகத்தில் நீங்களும் சேர்ந்துகொள்ளுங்கள். இது உண்மையிலேயே மிகச் சிறப்பான நாள்தான்!",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_99602",
    "storyId": "99602-raja-urvalam",
    "titleEn": "ராஜ ஊர்வலம்",
    "titleTa": "ராஜ ஊர்வலம்",
    "author": "Mahalakshmi",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/703492/size3/b7b9579f578a8043e0e9f143d5315a86.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/99602-raja-urvalam?mode=read",
    "descriptionEn": "பார்வதியும் அவளுடைய சகோதரன் இலக்குமனனும் பாடலிபுத்திர நகரில் வசிக்கிறார்கள் அவர்கள் அருகாமையிலுள்ள புத்த விஹாரத்திற்குக்  குடம், சட்டி போன்ற மட்பாண்டங்களைக் கொடுக்கச் சென்றபோது, அங்கு ஒரு சுவாரசியமான மனிதரைக் கண்டு நல்ல நட்பு கொண்டனர். அந்நபர் அவர்களிடம் தான் ஓர் ஓய்வுபெற்ற போர்வீரர் என்றும் பேரரசர் அசோகரின் அரண்மனையில் வேலை செய்வதாகவும், மாமன்னரைப் பார்க்க அவ்விருவர் கொண்டிருந்த அவா சீக்கிரத்தில் நிறைவேறும் என்றும் கூறினார். பிறகு ஒருநாள், ராஜ ஊர்வலம் அவர்கள் வீட்டைத் தாண்டிச் சென்றபோது, அக்குழந்தைகளுக்கு ஒரு வியப்புமிக்க நிகழ்ச்சி காத்திருந்தது. அந்த வியப்புமிக்க சம்பவத்தைப் பற்றித் தெரிந்துகொள்ள, மௌரிய காலத்தில் பின்னப்பட்டுள்ள இந்த அருமையான கதையைப் படியுங்கள்!",
    "descriptionTa": "பார்வதியும் அவளுடைய சகோதரன் இலக்குமனனும் பாடலிபுத்திர நகரில் வசிக்கிறார்கள் அவர்கள் அருகாமையிலுள்ள புத்த விஹாரத்திற்குக்  குடம், சட்டி போன்ற மட்பாண்டங்களைக் கொடுக்கச் சென்றபோது, அங்கு ஒரு சுவாரசியமான மனிதரைக் கண்டு நல்ல நட்பு கொண்டனர். அந்நபர் அவர்களிடம் தான் ஓர் ஓய்வுபெற்ற போர்வீரர் என்றும் பேரரசர் அசோகரின் அரண்மனையில் வேலை செய்வதாகவும், மாமன்னரைப் பார்க்க அவ்விருவர் கொண்டிருந்த அவா சீக்கிரத்தில் நிறைவேறும் என்றும் கூறினார். பிறகு ஒருநாள், ராஜ ஊர்வலம் அவர்கள் வீட்டைத் தாண்டிச் சென்றபோது, அக்குழந்தைகளுக்கு ஒரு வியப்புமிக்க நிகழ்ச்சி காத்திருந்தது. அந்த வியப்புமிக்க சம்பவத்தைப் பற்றித் தெரிந்துகொள்ள, மௌரிய காலத்தில் பின்னப்பட்டுள்ள இந்த அருமையான கதையைப் படியுங்கள்!",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_5169",
    "storyId": "5169-manikantanukka-podum",
    "titleEn": "மணிகண்டனுக்குப் போதும்",
    "titleTa": "மணிகண்டனுக்குப் போதும்",
    "author": "S Krishnan",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/712349/size3/80baf01ee305956f7dc6a39548938ed4.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/5169-manikantanukka-podum?mode=read",
    "descriptionEn": "மணிகண்டனுடைய தாயத்து அவன் எப்போது மகிழ்ச்சியாக இருக்கிறான், எப்போது வருத்தமாக இருக்கிறான், உடல் நலத்தோடு இருக்கிறானா இல்லையா என்பதையெல்லாம் சொல்லிவிடும். எப்போது சாப்பிடவேண்டும், எப்போது தூங்கவேண்டும் என்பதைச் சொல்வது, அவன் வீட்டுப்பாடத்தைச் செய்வதற்கு உதவி செய்வது, அவன் நலமாக இல்லை என்பதை அம்மாவிடம் தெரியப்படுத்துவது போன்ற பல வேலைகளை அது செய்யும். இது மாயாஜாலமா, இல்லை அறிவியலா? மணிகண்டனும் அவன் அம்மாவும் கிராமத்திலிருந்து  ஒரு நவீன நகரத்துக்கு போகும்போது என்ன நடக்கிறதென்று பாருங்கள்.",
    "descriptionTa": "மணிகண்டனுடைய தாயத்து அவன் எப்போது மகிழ்ச்சியாக இருக்கிறான், எப்போது வருத்தமாக இருக்கிறான், உடல் நலத்தோடு இருக்கிறானா இல்லையா என்பதையெல்லாம் சொல்லிவிடும். எப்போது சாப்பிடவேண்டும், எப்போது தூங்கவேண்டும் என்பதைச் சொல்வது, அவன் வீட்டுப்பாடத்தைச் செய்வதற்கு உதவி செய்வது, அவன் நலமாக இல்லை என்பதை அம்மாவிடம் தெரியப்படுத்துவது போன்ற பல வேலைகளை அது செய்யும். இது மாயாஜாலமா, இல்லை அறிவியலா? மணிகண்டனும் அவன் அம்மாவும் கிராமத்திலிருந்து  ஒரு நவீன நகரத்துக்கு போகும்போது என்ன நடக்கிறதென்று பாருங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_52166",
    "storyId": "52166-inaiya-nanbarin-marmam",
    "titleEn": "இணைய நண்பரின் மர்மம்",
    "titleTa": "இணைய நண்பரின் மர்மம்",
    "author": "S Krishnan",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/717889/size3/8ee1bc5bd72569dbc8976fffc65deeb0.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/52166-inaiya-nanbarin-marmam?mode=read",
    "descriptionEn": "கணிணியில் புதிது புதிதாகக் கற்றுக்கொள்வதில் ஸ்ரீ ஆர்வமுடையவள். அதில் விளையாட்டுகளும் உண்டு, சமூக ஊடகங்களும் உண்டு! அங்கே ஒரு புதிய தோழியைப் பெற்றதில் அவள் உற்சாகமானாள். ஆனால் அவளுடைய தோழி பொய் சொல்கிறாளா, என்ன? இணையத்தை மையமாகக் கொண்ட இந்த விறுவிறுப்பான கதையில் அதைக் கண்டுபிடியுங்கள்.",
    "descriptionTa": "கணிணியில் புதிது புதிதாகக் கற்றுக்கொள்வதில் ஸ்ரீ ஆர்வமுடையவள். அதில் விளையாட்டுகளும் உண்டு, சமூக ஊடகங்களும் உண்டு! அங்கே ஒரு புதிய தோழியைப் பெற்றதில் அவள் உற்சாகமானாள். ஆனால் அவளுடைய தோழி பொய் சொல்கிறாளா, என்ன? இணையத்தை மையமாகக் கொண்ட இந்த விறுவிறுப்பான கதையில் அதைக் கண்டுபிடியுங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_53436",
    "storyId": "53436-echarikkai-karunthulai",
    "titleEn": "எச்சரிக்கை! கருந்துளை",
    "titleTa": "எச்சரிக்கை! கருந்துளை",
    "author": "Elavasa  Kothanar",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/717893/size3/fd72155d5f986ecb1b1e0afa27f5da77.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/53436-echarikkai-karunthulai?mode=read",
    "descriptionEn": "சூரியக் குடும்பத்தைச் சுற்றிப் பார்க்க பூமியிலிருந்து மூன்று நண்பர்கள் ஒரு விண்கலனில் ஏறிச் செல்கிறார்கள். அப்பொழுது திடீரென ஒரு கருந்துளையை நோக்கி இழுக்கப்படுகின்றனர். அவர்கள் தப்பித்தார்களா? இந்த விண்வெளிக் கதையில் என்ன நடக்கிறதென பார்க்கலாம் வாருங்கள்.",
    "descriptionTa": "சூரியக் குடும்பத்தைச் சுற்றிப் பார்க்க பூமியிலிருந்து மூன்று நண்பர்கள் ஒரு விண்கலனில் ஏறிச் செல்கிறார்கள். அப்பொழுது திடீரென ஒரு கருந்துளையை நோக்கி இழுக்கப்படுகின்றனர். அவர்கள் தப்பித்தார்களா? இந்த விண்வெளிக் கதையில் என்ன நடக்கிறதென பார்க்கலாம் வாருங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_38988",
    "storyId": "38988-kaatrin-edai-enna",
    "titleEn": "காற்றின் எடை என்ன?",
    "titleTa": "காற்றின் எடை என்ன?",
    "author": "S. Jayaraman",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://storage.googleapis.com/static.storyweaver.org.in/illustration_crops/725413/size3/ce76d232acdcbc97d22d67d7ad3defba.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/38988-kaatrin-edai-enna?mode=read",
    "descriptionEn": "பலூன்கள் வண்ணமயமானவையும் இலேசானவையும் ஆகும். அவை மிதப்பவை. ஊதப்பட்ட பலூனின் உள்ளே இருக்கும் காற்றுக்கும் எடையுள்ளதா? என்று லக்ஷ்மியைப் போலவே நீங்களும் ஆச்சரியப்படலாம். அவளும் அவள் வகுப்பினரும் காற்றுக்கு ஏதாவது எடை இருக்கிறதா என்பதைக் கண்டுபிடிக்கிறார்கள். அவர்கள் கற்றுக்கொண்டதை நீங்களும் தெரிந்துகொள்ள இந்தப் புத்தகத்தைப் படியுங்கள்.",
    "descriptionTa": "பலூன்கள் வண்ணமயமானவையும் இலேசானவையும் ஆகும். அவை மிதப்பவை. ஊதப்பட்ட பலூனின் உள்ளே இருக்கும் காற்றுக்கும் எடையுள்ளதா? என்று லக்ஷ்மியைப் போலவே நீங்களும் ஆச்சரியப்படலாம். அவளும் அவள் வகுப்பினரும் காற்றுக்கு ஏதாவது எடை இருக்கிறதா என்பதைக் கண்டுபிடிக்கிறார்கள். அவர்கள் கற்றுக்கொண்டதை நீங்களும் தெரிந்துகொள்ள இந்தப் புத்தகத்தைப் படியுங்கள்.",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  },
  {
    "id": "sw_86697",
    "storyId": "86697-lajjovin-puthaiyal-vettai",
    "titleEn": "லஜ்ஜோவின் புதையல் வேட்டை!",
    "titleTa": "லஜ்ஜோவின் புதையல் வேட்டை!",
    "author": "Nivedha",
    "level": "4",
    "levelLabelEn": "Level 4 (Fluent)",
    "levelLabelTa": "நிலை 4 (உயர் நிலை)",
    "targetGrades": "Year 6 - Year 9",
    "coverUrl": "https://static.storyweaver.org.in/illustration_crops/715245/size3/125c121033c3f1d3ae6712079658c840.jpg",
    "embedUrl": "https://storyweaver.org.in/en/stories/embed/reader/86697-lajjovin-puthaiyal-vettai?mode=read",
    "descriptionEn": "பட்டியலிலுள்ள அனைத்துப் பொருட்களையும் கண்டுபிடித்தால்தான் தாத்தாவுடனான இந்த விளையாட்டில் லஜ்ஜோ வெற்றிபெற முடியும். ஆனால் ஏன் இப்படியொரு விளையாட்டு என்று எல்லோருக்கும் குழப்பம்.  ஊரே பிரச்சினையில் உள்ளபோது எதற்காக இப்படியொரு விளையாட்டு?",
    "descriptionTa": "பட்டியலிலுள்ள அனைத்துப் பொருட்களையும் கண்டுபிடித்தால்தான் தாத்தாவுடனான இந்த விளையாட்டில் லஜ்ஜோ வெற்றிபெற முடியும். ஆனால் ஏன் இப்படியொரு விளையாட்டு என்று எல்லோருக்கும் குழப்பம்.  ஊரே பிரச்சினையில் உள்ளபோது எதற்காக இப்படியொரு விளையாட்டு?",
    "readingPoints": 80,
    "pagesCount": 16,
    "tags": []
  }
];
